[modules.shoppinglist]
source = ".dagger/modules/shoppinglist"
entrypoint = true

[modules.shoppinglist.settings]
registryPassword="file://./local/GH_API_KEY"
kubeEnv="file://./local/kubecfg_rpi.yaml"

[modules.backend]
source = "backend/.dagger"

[modules.dagger-go-sdk]
source = "github.com/dagger/go-sdk"

[modules.frontend]
source = "frontend/.dagger"


[sdks.go]
module = "dagger-go-sdk"

[sdks.go.scopes.".dagger/modules/helm"]
is-module = true
clients = ["github.com/dagger/dagger/toolchains/release/registry-config@d8811256e5e901e6760f7011431080fedd61fc47"]
name = "helm"

[sdks.go.scopes.".dagger/modules/shoppinglist"]
is-module = true
clients = ["./.dagger/modules/helm", "./backend/.dagger", "./frontend/.dagger"]
name = "shoppinglist"

[sdks.go.scopes."backend/.dagger"]
is-module = true
name = "backend"

[sdks.go.scopes."frontend/.dagger"]
is-module = true
name = "frontend"

[env.ci]

[env.ci.modules.shoppinglist.settings]
registryPassword = "env://GH_API_KEY"
kubeEnv = "env://KUBECTL_FILE"

