// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"dagger.io/dagger/querybuilder"
)

// The `BackendID` scalar type represents an identifier for an object of type Backend.
type BackendID string // backend (../../../backend/.dagger/main.go:25:6)

type Backend struct { // backend (../../../backend/.dagger/main.go:25:6)
	query *querybuilder.Selection

	checkProtos               *Void
	checkSqlc                 *Void
	checkTailwind             *Void
	checkTempl                *Void
	id                        *BackendID
	migrateCheck              *Void
	publish                   *Void
	testMigrationToolsNodb    *Void
	testMigrationToolsNodbenv *Void
	testMigrationToolsWithDb  *Void
}

func (r *Backend) WithGraphQLQuery(q *querybuilder.Selection) *Backend {
	return &Backend{
		query: q,
	}
}

// BackendBackendServiceOpts contains options for Backend.BackendService
type BackendBackendServiceOpts struct {
	Ws *Workspace // backend (../../../backend/.dagger/service.go:17:55)
}

// BackendService - runs the backend service inside a container
func (r *Backend) BackendService(opts ...BackendBackendServiceOpts) *Service { // backend (../../../backend/.dagger/service.go:17:1)
	q := r.query.Select("backendService")
	for i := len(opts) - 1; i >= 0; i-- {
		// `ws` optional argument
		if !querybuilder.IsZeroValue(opts[i].Ws) {
			q = q.Arg("ws", opts[i].Ws)
		}
	}

	return &Service{
		query: q,
	}
}

func (r *Backend) BuildCheck() *Container { // backend (../../../backend/.dagger/build.go:14:1)
	q := r.query.Select("buildCheck")

	return &Container{
		query: q,
	}
}

// CheckProtos - check that the working tree's proto generated files are in sync.
func (r *Backend) CheckProtos(ctx context.Context) error { // backend (../../../backend/.dagger/generated.go:26:1)
	if r.checkProtos != nil {
		return nil
	}
	q := r.query.Select("checkProtos")

	return q.Execute(ctx)
}

// CheckSqlc - check that the working tree's sqlc generated files are in sync.
func (r *Backend) CheckSqlc(ctx context.Context) error { // backend (../../../backend/.dagger/generated.go:47:1)
	if r.checkSqlc != nil {
		return nil
	}
	q := r.query.Select("checkSqlc")

	return q.Execute(ctx)
}

// CheckTailwind checks that maintw.css file is in sync
func (r *Backend) CheckTailwind(ctx context.Context) error { // backend (../../../backend/.dagger/generated_tailwind.go:27:1)
	if r.checkTailwind != nil {
		return nil
	}
	q := r.query.Select("checkTailwind")

	return q.Execute(ctx)
}

// CheckTempl - check that the working tree's templ generated files are in sync.
func (r *Backend) CheckTempl(ctx context.Context) error { // backend (../../../backend/.dagger/generated.go:67:1)
	if r.checkTempl != nil {
		return nil
	}
	q := r.query.Select("checkTempl")

	return q.Execute(ctx)
}

// GenerateProtos - generate protobuf codegen from .proto files
func (r *Backend) GenerateProtos() *Changeset { // backend (../../../backend/.dagger/generated.go:11:1)
	q := r.query.Select("generateProtos")

	return &Changeset{
		query: q,
	}
}

// GenerateSqlc - generate sqlc codegen from .sql files
func (r *Backend) GenerateSqlc() *Changeset { // backend (../../../backend/.dagger/generated.go:33:1)
	q := r.query.Select("generateSqlc")

	return &Changeset{
		query: q,
	}
}

// GenerateTailwind generates the maintw.css file using tailwindcss
func (r *Backend) GenerateTailwind() *Changeset { // backend (../../../backend/.dagger/generated_tailwind.go:12:1)
	q := r.query.Select("generateTailwind")

	return &Changeset{
		query: q,
	}
}

// GenerateTempl - generate templ codegen from .templ files
func (r *Backend) GenerateTempl() *Changeset { // backend (../../../backend/.dagger/generated.go:54:1)
	q := r.query.Select("generateTempl")

	return &Changeset{
		query: q,
	}
}

// A unique identifier for this Backend.
func (r *Backend) ID(ctx context.Context) (BackendID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response BackendID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Backend) XXX_GraphQLType() string {
	return "Backend"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Backend) XXX_GraphQLIDType() string {
	return "BackendID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Backend) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Backend) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Backend) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = *dag.LoadBackendFromID(BackendID(id))
	return nil
}

// MigrateCheck - checks whether the previous schema on the master branch
// can be successfully migrated to the new schema
func (r *Backend) MigrateCheck(ctx context.Context) error { // backend (../../../backend/.dagger/migrate.go:23:1)
	if r.migrateCheck != nil {
		return nil
	}
	q := r.query.Select("migrateCheck")

	return q.Execute(ctx)
}

// MigrateLocal - migrates the passed in database and returns it
func (r *Backend) MigrateLocal(localdb *File) *File { // backend (../../../backend/.dagger/migrate.go:14:1)
	assertNotNil("localdb", localdb)
	q := r.query.Select("migrateLocal")
	q = q.Arg("localdb", localdb)

	return &File{
		query: q,
	}
}

func (r *Backend) Publish(ctx context.Context, tag string, registryPassword *Secret) error { // backend (../../../backend/.dagger/main.go:42:1)
	assertNotNil("registryPassword", registryPassword)
	if r.publish != nil {
		return nil
	}
	q := r.query.Select("publish")
	q = q.Arg("tag", tag)
	q = q.Arg("registryPassword", registryPassword)

	return q.Execute(ctx)
}

// TestMigrationToolsNODB - tests that the migration tools work if the DB doesn't exist
func (r *Backend) TestMigrationToolsNodb(ctx context.Context) error { // backend (../../../backend/.dagger/migration_tools.go:46:1)
	if r.testMigrationToolsNodb != nil {
		return nil
	}
	q := r.query.Select("testMigrationToolsNodb")

	return q.Execute(ctx)
}

// TestMigrationToolsNoDBEnv - tests that the migration tools correctly fail if the DATABASE_FILE var isn't present
func (r *Backend) TestMigrationToolsNodbenv(ctx context.Context) error { // backend (../../../backend/.dagger/migration_tools.go:59:1)
	if r.testMigrationToolsNodbenv != nil {
		return nil
	}
	q := r.query.Select("testMigrationToolsNodbenv")

	return q.Execute(ctx)
}

// TestMigrationToolsWithDB - tests that the migration tools work if the DB exists
func (r *Backend) TestMigrationToolsWithDb(ctx context.Context) error { // backend (../../../backend/.dagger/migration_tools.go:28:1)
	if r.testMigrationToolsWithDb != nil {
		return nil
	}
	q := r.query.Select("testMigrationToolsWithDb")

	return q.Execute(ctx)
}

// Retrieve the binding value, as type Backend
func (r *Binding) AsBackend() *Backend { // backend (../../../backend/.dagger/main.go:25:6)
	q := r.query.Select("asBackend")

	return &Backend{
		query: q,
	}
}

// Create or update a binding of type Backend in the environment
func (r *Env) WithBackendInput(name string, value *Backend, description string) *Env { // backend (../../../backend/.dagger/main.go:25:6)
	assertNotNil("value", value)
	q := r.query.Select("withBackendInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Backend output to be assigned in the environment
func (r *Env) WithBackendOutput(name string, description string) *Env { // backend (../../../backend/.dagger/main.go:25:6)
	q := r.query.Select("withBackendOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// BackendOpts contains options for Query.Backend
type BackendOpts struct {
	Ws *Workspace // backend (../../../backend/.dagger/main.go:33:2)
}

// A generated module for Backend functions
//
// This module has been generated via dagger init and serves as a reference to
// basic module structure as you get started with Dagger.
//
// Two functions have been pre-created. You can modify, delete, or add to them,
// as needed. They demonstrate usage of arguments and return types using simple
// echo and grep commands. The functions can be called from the dagger CLI or
// from one of the SDKs.
//
// The first line in this comment block is a short description line and the
// rest is a long description with more detail on the module's purpose or usage,
// if appropriate. All modules should have a short description.
func (r *Query) Backend(opts ...BackendOpts) *Backend { // backend (../../../backend/.dagger/main.go:32:1)
	q := r.query.Select("backend")
	for i := len(opts) - 1; i >= 0; i-- {
		// `ws` optional argument
		if !querybuilder.IsZeroValue(opts[i].Ws) {
			q = q.Arg("ws", opts[i].Ws)
		}
	}

	return &Backend{
		query: q,
	}
}

// Load a Backend from its ID.
func (r *Query) LoadBackendFromID(id BackendID) *Backend { // backend (../../../backend/.dagger/main.go:25:6)
	q := r.query.Select("loadBackendFromID")
	q = q.Arg("id", id)

	return &Backend{
		query: q,
	}
}
