// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Frontend
func (r *Binding) AsFrontend() *Frontend { // frontend (../../../frontend/.dagger/main.go:30:6)
	q := r.query.Select("asFrontend")

	return &Frontend{
		query: q,
	}
}

// Create or update a binding of type Frontend in the environment
func (r *Env) WithFrontendInput(name string, value *Frontend, description string) *Env { // frontend (../../../frontend/.dagger/main.go:30:6)
	assertNotNil("value", value)
	q := r.query.Select("withFrontendInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Frontend output to be assigned in the environment
func (r *Env) WithFrontendOutput(name string, description string) *Env { // frontend (../../../frontend/.dagger/main.go:30:6)
	q := r.query.Select("withFrontendOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

type Frontend struct { // frontend (../../../frontend/.dagger/main.go:30:6)
	query *querybuilder.Selection

	id      *ID
	publish *Void
}

func (r *Frontend) WithGraphQLQuery(q *querybuilder.Selection) *Frontend {
	return &Frontend{
		query: q,
	}
}

func (r *Frontend) BuildCheck() *Container { // frontend (../../../frontend/.dagger/main.go:46:1)
	q := r.query.Select("buildCheck")

	return &Container{
		query: q,
	}
}

// FrontendService - runs the frontend service inside a container
func (r *Frontend) FrontendService() *Service { // frontend (../../../frontend/.dagger/service.go:25:1)
	q := r.query.Select("frontendService")

	return &Service{
		query: q,
	}
}

// GenerateProtos - generate protobuf codegen from .proto files
func (r *Frontend) GenerateProtos() *Changeset { // frontend (../../../frontend/.dagger/generated.go:9:1)
	q := r.query.Select("generateProtos")

	return &Changeset{
		query: q,
	}
}

// A unique identifier for this Frontend.
func (r *Frontend) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Frontend) XXX_GraphQLType() string {
	return "Frontend"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Frontend) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Frontend) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Frontend) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Frontend) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Frontend{query: selectNode(dag.query, id, "Frontend")}
	return nil
}

func (r *Frontend) Publish(ctx context.Context, tag string, registryPassword *Secret) error { // frontend (../../../frontend/.dagger/main.go:89:1)
	assertNotNil("registryPassword", registryPassword)
	if r.publish != nil {
		return nil
	}
	q := r.query.Select("publish")
	q = q.Arg("tag", tag)
	q = q.Arg("registryPassword", registryPassword)

	return q.Execute(ctx)
}

func (r *Frontend) Src() *Directory { // frontend (../../../frontend/.dagger/main.go:33:2)
	q := r.query.Select("src")

	return &Directory{
		query: q,
	}
}

// AsNode returns this Frontend as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Frontend) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// FrontendOpts contains options for Query.Frontend
type FrontendOpts struct {
	Ws *Workspace // frontend (../../../frontend/.dagger/main.go:37:2)
}

// A generated module for Frontend functions
//
// This module has been generated via dagger init and serves as a reference to
// basic module structure as you get started with Dagger.
//
// Two functions have been pre-created. You can modify, delete, or add to them,
// as needed. They demonstrate usage of arguments and return types using simple
// echo and grep commands. The functions can be called from the dagger CLI or
// from one of the SDKs.
//
// The first line in this comment block is a short description line and the
// rest is a long description with more detail on the module's purpose or usage,
// if appropriate. All modules should have a short description.
func (r *Query) Frontend(opts ...FrontendOpts) *Frontend { // frontend (../../../frontend/.dagger/main.go:36:1)
	q := r.query.Select("frontend")
	for i := len(opts) - 1; i >= 0; i-- {
		// `ws` optional argument
		if !querybuilder.IsZeroValue(opts[i].Ws) {
			q = q.Arg("ws", opts[i].Ws)
		}
	}

	return &Frontend{
		query: q,
	}
}
