// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"dagger.io/dagger/querybuilder"
)

// The `HelmChartID` scalar type represents an identifier for an object of type HelmChart.
type HelmChartID string // helm (../../../dagger-helm/chart.go:20:6)

// The `HelmID` scalar type represents an identifier for an object of type Helm.
type HelmID string // helm (../../../dagger-helm/main.go:17:6)

// The `HelmPackageID` scalar type represents an identifier for an object of type HelmPackage.
type HelmPackageID string // helm (../../../dagger-helm/chart.go:33:6)

// The `HelmReleaseID` scalar type represents an identifier for an object of type HelmRelease.
type HelmReleaseID string // helm (../../../dagger-helm/release.go:637:6)

// Retrieve the binding value, as type Helm
func (r *Binding) AsHelm() *Helm { // helm (../../../dagger-helm/main.go:17:6)
	q := r.query.Select("asHelm")

	return &Helm{
		query: q,
	}
}

// Retrieve the binding value, as type HelmChart
func (r *Binding) AsHelmChart() *HelmChart { // helm (../../../dagger-helm/chart.go:20:6)
	q := r.query.Select("asHelmChart")

	return &HelmChart{
		query: q,
	}
}

// Retrieve the binding value, as type HelmPackage
func (r *Binding) AsHelmPackage() *HelmPackage { // helm (../../../dagger-helm/chart.go:33:6)
	q := r.query.Select("asHelmPackage")

	return &HelmPackage{
		query: q,
	}
}

// Retrieve the binding value, as type HelmRelease
func (r *Binding) AsHelmRelease() *HelmRelease { // helm (../../../dagger-helm/release.go:637:6)
	q := r.query.Select("asHelmRelease")

	return &HelmRelease{
		query: q,
	}
}

// Create or update a binding of type HelmChart in the environment
func (r *Env) WithHelmChartInput(name string, value *HelmChart, description string) *Env { // helm (../../../dagger-helm/chart.go:20:6)
	assertNotNil("value", value)
	q := r.query.Select("withHelmChartInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired HelmChart output to be assigned in the environment
func (r *Env) WithHelmChartOutput(name string, description string) *Env { // helm (../../../dagger-helm/chart.go:20:6)
	q := r.query.Select("withHelmChartOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type Helm in the environment
func (r *Env) WithHelmInput(name string, value *Helm, description string) *Env { // helm (../../../dagger-helm/main.go:17:6)
	assertNotNil("value", value)
	q := r.query.Select("withHelmInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Helm output to be assigned in the environment
func (r *Env) WithHelmOutput(name string, description string) *Env { // helm (../../../dagger-helm/main.go:17:6)
	q := r.query.Select("withHelmOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type HelmPackage in the environment
func (r *Env) WithHelmPackageInput(name string, value *HelmPackage, description string) *Env { // helm (../../../dagger-helm/chart.go:33:6)
	assertNotNil("value", value)
	q := r.query.Select("withHelmPackageInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired HelmPackage output to be assigned in the environment
func (r *Env) WithHelmPackageOutput(name string, description string) *Env { // helm (../../../dagger-helm/chart.go:33:6)
	q := r.query.Select("withHelmPackageOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type HelmRelease in the environment
func (r *Env) WithHelmReleaseInput(name string, value *HelmRelease, description string) *Env { // helm (../../../dagger-helm/release.go:637:6)
	assertNotNil("value", value)
	q := r.query.Select("withHelmReleaseInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired HelmRelease output to be assigned in the environment
func (r *Env) WithHelmReleaseOutput(name string, description string) *Env { // helm (../../../dagger-helm/release.go:637:6)
	q := r.query.Select("withHelmReleaseOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

type Helm struct { // helm (../../../dagger-helm/main.go:17:6)
	query *querybuilder.Selection

	id   *HelmID
	push *Void
}
type WithHelmFunc func(r *Helm) *Helm

// With calls the provided function with current Helm.
//
// This is useful for reusability and readability by not breaking the calling chain.
func (r *Helm) With(f WithHelmFunc) *Helm {
	return f(r)
}

func (r *Helm) WithGraphQLQuery(q *querybuilder.Selection) *Helm {
	return &Helm{
		query: q,
	}
}

// Returns a Helm chart from a source directory.
func (r *Helm) Chart(source *Directory) *HelmChart { // helm (../../../dagger-helm/chart.go:9:1)
	assertNotNil("source", source)
	q := r.query.Select("chart")
	q = q.Arg("source", source)

	return &HelmChart{
		query: q,
	}
}

func (r *Helm) Container() *Container { // helm (../../../dagger-helm/main.go:18:2)
	q := r.query.Select("container")

	return &Container{
		query: q,
	}
}

// Create a new chart directory along with the common files and directories used in a chart.
func (r *Helm) Create(name string) *HelmChart { // helm (../../../dagger-helm/main.go:108:1)
	q := r.query.Select("create")
	q = q.Arg("name", name)

	return &HelmChart{
		query: q,
	}
}

// A unique identifier for this Helm.
func (r *Helm) ID(ctx context.Context) (HelmID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response HelmID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Helm) XXX_GraphQLType() string {
	return "Helm"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Helm) XXX_GraphQLIDType() string {
	return "HelmID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Helm) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Helm) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Helm) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = *dag.LoadHelmFromID(HelmID(id))
	return nil
}

// Lint a Helm chart directory.
func (r *Helm) Lint(chart *Directory) *Container { // helm (../../../dagger-helm/main.go:122:1)
	assertNotNil("chart", chart)
	q := r.query.Select("lint")
	q = q.Arg("chart", chart)

	return &Container{
		query: q,
	}
}

// HelmLoginOpts contains options for Helm.Login
type HelmLoginOpts struct {
	//
	// Allow connections to TLS registry without certs.
	//
	Insecure bool // helm (../../../dagger-helm/main.go:229:2)
}

// Authenticate to an OCI registry.
//
// Note: Login stores credentials in the filesystem in plain text. Use WithRegistryAuth as a safer alternative.
func (r *Helm) Login(host string, username string, password *Secret, opts ...HelmLoginOpts) *Helm { // helm (../../../dagger-helm/main.go:214:1)
	assertNotNil("password", password)
	q := r.query.Select("login")
	for i := len(opts) - 1; i >= 0; i-- {
		// `insecure` optional argument
		if !querybuilder.IsZeroValue(opts[i].Insecure) {
			q = q.Arg("insecure", opts[i].Insecure)
		}
	}
	q = q.Arg("host", host)
	q = q.Arg("username", username)
	q = q.Arg("password", password)

	return &Helm{
		query: q,
	}
}

// Remove credentials stored for an OCI registry.
func (r *Helm) Logout(host string) *Helm { // helm (../../../dagger-helm/main.go:253:1)
	q := r.query.Select("logout")
	q = q.Arg("host", host)

	return &Helm{
		query: q,
	}
}

// HelmPackageOpts contains options for Helm.Package
type HelmPackageOpts struct {
	//
	// Set the appVersion on the chart to this version.
	//
	AppVersion string // helm (../../../dagger-helm/main.go:159:2)
	//
	// Set the version on the chart to this semver version.
	//
	Version string // helm (../../../dagger-helm/main.go:164:2)
	//
	// Update dependencies from "Chart.yaml" to dir "charts/" before packaging.
	//
	DependencyUpdate bool // helm (../../../dagger-helm/main.go:169:2)
}

// Build a Helm chart package.
func (r *Helm) Package(chart *Directory, opts ...HelmPackageOpts) *File { // helm (../../../dagger-helm/main.go:150:1)
	assertNotNil("chart", chart)
	q := r.query.Select("package")
	for i := len(opts) - 1; i >= 0; i-- {
		// `appVersion` optional argument
		if !querybuilder.IsZeroValue(opts[i].AppVersion) {
			q = q.Arg("appVersion", opts[i].AppVersion)
		}
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
		// `dependencyUpdate` optional argument
		if !querybuilder.IsZeroValue(opts[i].DependencyUpdate) {
			q = q.Arg("dependencyUpdate", opts[i].DependencyUpdate)
		}
	}
	q = q.Arg("chart", chart)

	return &File{
		query: q,
	}
}

// HelmPushOpts contains options for Helm.Push
type HelmPushOpts struct {
	//
	// Use insecure HTTP connections for the chart upload.
	//
	PlainHTTP bool // helm (../../../dagger-helm/main.go:279:2)
	//
	// Skip tls certificate checks for the chart upload.
	//
	InsecureSkipTLSVerify bool // helm (../../../dagger-helm/main.go:284:2)
	//
	// Verify certificates of HTTPS-enabled servers using this CA bundle.
	//
	CaFile *File // helm (../../../dagger-helm/main.go:289:2)
	//
	// Identify registry client using this SSL certificate file.
	//
	CertFile *File // helm (../../../dagger-helm/main.go:294:2)
	//
	// Identify registry client using this SSL key file.
	//
	KeyFile *Secret // helm (../../../dagger-helm/main.go:299:2)
}

// Push a Helm chart package to an OCI registry.
func (r *Helm) Push(ctx context.Context, pkg *File, registry string, opts ...HelmPushOpts) error { // helm (../../../dagger-helm/main.go:267:1)
	assertNotNil("pkg", pkg)
	if r.push != nil {
		return nil
	}
	q := r.query.Select("push")
	for i := len(opts) - 1; i >= 0; i-- {
		// `plainHttp` optional argument
		if !querybuilder.IsZeroValue(opts[i].PlainHTTP) {
			q = q.Arg("plainHttp", opts[i].PlainHTTP)
		}
		// `insecureSkipTlsVerify` optional argument
		if !querybuilder.IsZeroValue(opts[i].InsecureSkipTLSVerify) {
			q = q.Arg("insecureSkipTlsVerify", opts[i].InsecureSkipTLSVerify)
		}
		// `caFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].CaFile) {
			q = q.Arg("caFile", opts[i].CaFile)
		}
		// `certFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].CertFile) {
			q = q.Arg("certFile", opts[i].CertFile)
		}
		// `keyFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].KeyFile) {
			q = q.Arg("keyFile", opts[i].KeyFile)
		}
	}
	q = q.Arg("pkg", pkg)
	q = q.Arg("registry", registry)

	return q.Execute(ctx)
}

// Mount a file as the kubeconfig file.
func (r *Helm) WithKubeconfigFile(file *File) *Helm { // helm (../../../dagger-helm/main.go:90:1)
	assertNotNil("file", file)
	q := r.query.Select("withKubeconfigFile")
	q = q.Arg("file", file)

	return &Helm{
		query: q,
	}
}

// Mount a secret as the kubeconfig file.
func (r *Helm) WithKubeconfigSecret(secret *Secret) *Helm { // helm (../../../dagger-helm/main.go:99:1)
	assertNotNil("secret", secret)
	q := r.query.Select("withKubeconfigSecret")
	q = q.Arg("secret", secret)

	return &Helm{
		query: q,
	}
}

// Add credentials for a registry.
//
// Note: WithRegistryAuth overrides any previous or subsequent calls to Login/Logout.
func (r *Helm) WithRegistryAuth(address string, username string, secret *Secret) *Helm { // helm (../../../dagger-helm/main.go:76:1)
	assertNotNil("secret", secret)
	q := r.query.Select("withRegistryAuth")
	q = q.Arg("address", address)
	q = q.Arg("username", username)
	q = q.Arg("secret", secret)

	return &Helm{
		query: q,
	}
}

// Removes credentials for a registry.
func (r *Helm) WithoutRegistryAuth(address string) *Helm { // helm (../../../dagger-helm/main.go:83:1)
	q := r.query.Select("withoutRegistryAuth")
	q = q.Arg("address", address)

	return &Helm{
		query: q,
	}
}

// A Helm chart.
type HelmChart struct { // helm (../../../dagger-helm/chart.go:20:6)
	query *querybuilder.Selection

	id *HelmChartID
}

func (r *HelmChart) WithGraphQLQuery(q *querybuilder.Selection) *HelmChart {
	return &HelmChart{
		query: q,
	}
}

func (r *HelmChart) Directory() *Directory { // helm (../../../dagger-helm/chart.go:21:2)
	q := r.query.Select("directory")

	return &Directory{
		query: q,
	}
}

// A unique identifier for this HelmChart.
func (r *HelmChart) ID(ctx context.Context) (HelmChartID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response HelmChartID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *HelmChart) XXX_GraphQLType() string {
	return "HelmChart"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *HelmChart) XXX_GraphQLIDType() string {
	return "HelmChartID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *HelmChart) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *HelmChart) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *HelmChart) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = *dag.LoadHelmChartFromID(HelmChartID(id))
	return nil
}

// HelmChartInstallOpts contains options for HelmChart.Install
type HelmChartInstallOpts struct {
	//
	// If set, the installation process deletes the installation on failure. Wait flag will be set automatically if atomic is used.
	//
	Atomic bool // helm (../../../dagger-helm/release.go:22:2)
	//
	// Verify certificates of HTTPS-enabled servers using this CA bundle.
	//
	CaFile *File // helm (../../../dagger-helm/release.go:27:2)
	//
	// Identify HTTPS client using this SSL certificate file.
	//
	CertFile *File // helm (../../../dagger-helm/release.go:32:2)
	//
	// Create the release namespace if not present.
	//
	CreateNamespace bool // helm (../../../dagger-helm/release.go:37:2)
	//
	// Update dependencies if they are missing before installing the chart.
	//
	DependencyUpdate bool // helm (../../../dagger-helm/release.go:42:2)
	//
	// Add a custom description.
	//
	Description string // helm (../../../dagger-helm/release.go:47:2)
	//
	// If set, the installation process will not validate rendered templates against the Kubernetes OpenAPI Schema.
	//
	DisableOpenapiValidation bool // helm (../../../dagger-helm/release.go:52:2)
	//
	// Enable DNS lookups when rendering templates.
	//
	EnableDNS bool // helm (../../../dagger-helm/release.go:62:2)
	//
	// Force resource updates through a replacement strategy.
	//
	Force bool // helm (../../../dagger-helm/release.go:67:2)
	//
	// Generate the name.
	//
	GenerateName bool // helm (../../../dagger-helm/release.go:72:2)
	//
	// Skip tls certificate checks for the chart download.
	//
	InsecureSkipTLSVerify bool // helm (../../../dagger-helm/release.go:82:2)
	//
	// Identify HTTPS client using this SSL key file.
	//
	KeyFile *Secret // helm (../../../dagger-helm/release.go:87:2)
	//
	// Labels that would be added to release metadata.
	//
	Labels []string // helm (../../../dagger-helm/release.go:92:2)
	//
	// Specify template used to name the release.
	//
	NameTemplate string // helm (../../../dagger-helm/release.go:97:2)
	//
	// Prevent hooks from running during install.
	//
	NoHooks bool // helm (../../../dagger-helm/release.go:102:2)
	//
	// Use insecure HTTP connections for the chart download.
	//
	PlainHTTP bool // helm (../../../dagger-helm/release.go:111:2)
	//
	// The path to an executable to be used for post rendering. If it exists in $PATH, the binary will be used, otherwise it will try to look for the executable at the given path.
	//
	PostRenderer string // helm (../../../dagger-helm/release.go:116:2)
	//
	// Arguments to the post-renderer.
	//
	PostRendererArgs []string // helm (../../../dagger-helm/release.go:121:2)
	//
	// If set, render subchart notes along with the parent.
	//
	RenderSubchartNotes bool // helm (../../../dagger-helm/release.go:126:2)
	//
	// Re-use the given name, only if that name is a deleted release which remains in the history. This is unsafe in production.
	//
	Replace bool // helm (../../../dagger-helm/release.go:131:2)
	//
	// If set, no CRDs will be installed. By default, CRDs are installed if not already present.
	//
	SkipCrds bool // helm (../../../dagger-helm/release.go:144:2)
	//
	// Time to wait for any individual Kubernetes operation (like Jobs for hooks).
	//
	Timeout string // helm (../../../dagger-helm/release.go:149:2)
	//
	// Specify values in a YAML file.
	//
	Values []*File // helm (../../../dagger-helm/release.go:156:2)
	//
	// Verify the package before using it.
	//
	Verify bool // helm (../../../dagger-helm/release.go:161:2)
	//
	// If set, will wait until all Pods, PVCs, Services, and minimum number of Pods of a Deployment, StatefulSet, or ReplicaSet are in a ready state before marking the release as successful. It will wait for as long as timeout.
	//
	Wait bool // helm (../../../dagger-helm/release.go:166:2)
	//
	// If set and wait enabled, will wait until all Jobs have been completed before marking the release as successful. It will wait for as long as timeout.
	//
	WaitForJobs bool // helm (../../../dagger-helm/release.go:171:2)
	//
	// Namespace scope for this request.
	//
	Namespace string // helm (../../../dagger-helm/release.go:178:2)
}

// Install a Helm chart.
func (r *HelmChart) Install(name string, opts ...HelmChartInstallOpts) *HelmRelease { // helm (../../../dagger-helm/release.go:13:1)
	q := r.query.Select("install")
	for i := len(opts) - 1; i >= 0; i-- {
		// `atomic` optional argument
		if !querybuilder.IsZeroValue(opts[i].Atomic) {
			q = q.Arg("atomic", opts[i].Atomic)
		}
		// `caFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].CaFile) {
			q = q.Arg("caFile", opts[i].CaFile)
		}
		// `certFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].CertFile) {
			q = q.Arg("certFile", opts[i].CertFile)
		}
		// `createNamespace` optional argument
		if !querybuilder.IsZeroValue(opts[i].CreateNamespace) {
			q = q.Arg("createNamespace", opts[i].CreateNamespace)
		}
		// `dependencyUpdate` optional argument
		if !querybuilder.IsZeroValue(opts[i].DependencyUpdate) {
			q = q.Arg("dependencyUpdate", opts[i].DependencyUpdate)
		}
		// `description` optional argument
		if !querybuilder.IsZeroValue(opts[i].Description) {
			q = q.Arg("description", opts[i].Description)
		}
		// `disableOpenapiValidation` optional argument
		if !querybuilder.IsZeroValue(opts[i].DisableOpenapiValidation) {
			q = q.Arg("disableOpenapiValidation", opts[i].DisableOpenapiValidation)
		}
		// `enableDns` optional argument
		if !querybuilder.IsZeroValue(opts[i].EnableDNS) {
			q = q.Arg("enableDns", opts[i].EnableDNS)
		}
		// `force` optional argument
		if !querybuilder.IsZeroValue(opts[i].Force) {
			q = q.Arg("force", opts[i].Force)
		}
		// `generateName` optional argument
		if !querybuilder.IsZeroValue(opts[i].GenerateName) {
			q = q.Arg("generateName", opts[i].GenerateName)
		}
		// `insecureSkipTlsVerify` optional argument
		if !querybuilder.IsZeroValue(opts[i].InsecureSkipTLSVerify) {
			q = q.Arg("insecureSkipTlsVerify", opts[i].InsecureSkipTLSVerify)
		}
		// `keyFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].KeyFile) {
			q = q.Arg("keyFile", opts[i].KeyFile)
		}
		// `labels` optional argument
		if !querybuilder.IsZeroValue(opts[i].Labels) {
			q = q.Arg("labels", opts[i].Labels)
		}
		// `nameTemplate` optional argument
		if !querybuilder.IsZeroValue(opts[i].NameTemplate) {
			q = q.Arg("nameTemplate", opts[i].NameTemplate)
		}
		// `noHooks` optional argument
		if !querybuilder.IsZeroValue(opts[i].NoHooks) {
			q = q.Arg("noHooks", opts[i].NoHooks)
		}
		// `plainHttp` optional argument
		if !querybuilder.IsZeroValue(opts[i].PlainHTTP) {
			q = q.Arg("plainHttp", opts[i].PlainHTTP)
		}
		// `postRenderer` optional argument
		if !querybuilder.IsZeroValue(opts[i].PostRenderer) {
			q = q.Arg("postRenderer", opts[i].PostRenderer)
		}
		// `postRendererArgs` optional argument
		if !querybuilder.IsZeroValue(opts[i].PostRendererArgs) {
			q = q.Arg("postRendererArgs", opts[i].PostRendererArgs)
		}
		// `renderSubchartNotes` optional argument
		if !querybuilder.IsZeroValue(opts[i].RenderSubchartNotes) {
			q = q.Arg("renderSubchartNotes", opts[i].RenderSubchartNotes)
		}
		// `replace` optional argument
		if !querybuilder.IsZeroValue(opts[i].Replace) {
			q = q.Arg("replace", opts[i].Replace)
		}
		// `skipCrds` optional argument
		if !querybuilder.IsZeroValue(opts[i].SkipCrds) {
			q = q.Arg("skipCrds", opts[i].SkipCrds)
		}
		// `timeout` optional argument
		if !querybuilder.IsZeroValue(opts[i].Timeout) {
			q = q.Arg("timeout", opts[i].Timeout)
		}
		// `values` optional argument
		if !querybuilder.IsZeroValue(opts[i].Values) {
			q = q.Arg("values", opts[i].Values)
		}
		// `verify` optional argument
		if !querybuilder.IsZeroValue(opts[i].Verify) {
			q = q.Arg("verify", opts[i].Verify)
		}
		// `wait` optional argument
		if !querybuilder.IsZeroValue(opts[i].Wait) {
			q = q.Arg("wait", opts[i].Wait)
		}
		// `waitForJobs` optional argument
		if !querybuilder.IsZeroValue(opts[i].WaitForJobs) {
			q = q.Arg("waitForJobs", opts[i].WaitForJobs)
		}
		// `namespace` optional argument
		if !querybuilder.IsZeroValue(opts[i].Namespace) {
			q = q.Arg("namespace", opts[i].Namespace)
		}
	}
	q = q.Arg("name", name)

	return &HelmRelease{
		query: q,
	}
}

// Lint a Helm chart.
func (r *HelmChart) Lint() *Container { // helm (../../../dagger-helm/chart.go:28:1)
	q := r.query.Select("lint")

	return &Container{
		query: q,
	}
}

// HelmChartPackageOpts contains options for HelmChart.Package
type HelmChartPackageOpts struct {
	//
	// Set the appVersion on the chart to this version.
	//
	AppVersion string // helm (../../../dagger-helm/chart.go:50:2)
	//
	// Set the version on the chart to this semver version.
	//
	Version string // helm (../../../dagger-helm/chart.go:55:2)
	//
	// Update dependencies from "Chart.yaml" to dir "charts/" before packaging.
	//
	DependencyUpdate bool // helm (../../../dagger-helm/chart.go:60:2)
}

// Build a Helm chart package.
func (r *HelmChart) Package(opts ...HelmChartPackageOpts) *HelmPackage { // helm (../../../dagger-helm/chart.go:44:1)
	q := r.query.Select("package")
	for i := len(opts) - 1; i >= 0; i-- {
		// `appVersion` optional argument
		if !querybuilder.IsZeroValue(opts[i].AppVersion) {
			q = q.Arg("appVersion", opts[i].AppVersion)
		}
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
		// `dependencyUpdate` optional argument
		if !querybuilder.IsZeroValue(opts[i].DependencyUpdate) {
			q = q.Arg("dependencyUpdate", opts[i].DependencyUpdate)
		}
	}

	return &HelmPackage{
		query: q,
	}
}

// A Helm chart package.
type HelmPackage struct { // helm (../../../dagger-helm/chart.go:33:6)
	query *querybuilder.Selection

	id      *HelmPackageID
	publish *Void
}
type WithHelmPackageFunc func(r *HelmPackage) *HelmPackage

// With calls the provided function with current HelmPackage.
//
// This is useful for reusability and readability by not breaking the calling chain.
func (r *HelmPackage) With(f WithHelmPackageFunc) *HelmPackage {
	return f(r)
}

func (r *HelmPackage) WithGraphQLQuery(q *querybuilder.Selection) *HelmPackage {
	return &HelmPackage{
		query: q,
	}
}

func (r *HelmPackage) File() *File { // helm (../../../dagger-helm/chart.go:34:2)
	q := r.query.Select("file")

	return &File{
		query: q,
	}
}

// A unique identifier for this HelmPackage.
func (r *HelmPackage) ID(ctx context.Context) (HelmPackageID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response HelmPackageID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *HelmPackage) XXX_GraphQLType() string {
	return "HelmPackage"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *HelmPackage) XXX_GraphQLIDType() string {
	return "HelmPackageID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *HelmPackage) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *HelmPackage) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *HelmPackage) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = *dag.LoadHelmPackageFromID(HelmPackageID(id))
	return nil
}

// HelmPackageInstallOpts contains options for HelmPackage.Install
type HelmPackageInstallOpts struct {
	//
	// If set, the installation process deletes the installation on failure. Wait flag will be set automatically if atomic is used.
	//
	Atomic bool // helm (../../../dagger-helm/release.go:241:2)
	//
	// Verify certificates of HTTPS-enabled servers using this CA bundle.
	//
	CaFile *File // helm (../../../dagger-helm/release.go:246:2)
	//
	// Identify HTTPS client using this SSL certificate file.
	//
	CertFile *File // helm (../../../dagger-helm/release.go:251:2)
	//
	// Create the release namespace if not present.
	//
	CreateNamespace bool // helm (../../../dagger-helm/release.go:256:2)
	//
	// Update dependencies if they are missing before installing the chart.
	//
	DependencyUpdate bool // helm (../../../dagger-helm/release.go:261:2)
	//
	// Add a custom description.
	//
	Description string // helm (../../../dagger-helm/release.go:266:2)
	//
	// If set, the installation process will not validate rendered templates against the Kubernetes OpenAPI Schema.
	//
	DisableOpenapiValidation bool // helm (../../../dagger-helm/release.go:271:2)
	//
	// Enable DNS lookups when rendering templates.
	//
	EnableDNS bool // helm (../../../dagger-helm/release.go:281:2)
	//
	// Force resource updates through a replacement strategy.
	//
	Force bool // helm (../../../dagger-helm/release.go:286:2)
	//
	// Generate the name.
	//
	GenerateName bool // helm (../../../dagger-helm/release.go:291:2)
	//
	// Skip tls certificate checks for the chart download.
	//
	InsecureSkipTLSVerify bool // helm (../../../dagger-helm/release.go:301:2)
	//
	// Identify HTTPS client using this SSL key file.
	//
	KeyFile *Secret // helm (../../../dagger-helm/release.go:306:2)
	//
	// Labels that would be added to release metadata.
	//
	Labels []string // helm (../../../dagger-helm/release.go:311:2)
	//
	// Specify template used to name the release.
	//
	NameTemplate string // helm (../../../dagger-helm/release.go:316:2)
	//
	// Prevent hooks from running during install.
	//
	NoHooks bool // helm (../../../dagger-helm/release.go:321:2)
	//
	// Use insecure HTTP connections for the chart download.
	//
	PlainHTTP bool // helm (../../../dagger-helm/release.go:330:2)
	//
	// The path to an executable to be used for post rendering. If it exists in $PATH, the binary will be used, otherwise it will try to look for the executable at the given path.
	//
	PostRenderer string // helm (../../../dagger-helm/release.go:335:2)
	//
	// Arguments to the post-renderer.
	//
	PostRendererArgs []string // helm (../../../dagger-helm/release.go:340:2)
	//
	// If set, render subchart notes along with the parent.
	//
	RenderSubchartNotes bool // helm (../../../dagger-helm/release.go:345:2)
	//
	// Re-use the given name, only if that name is a deleted release which remains in the history. This is unsafe in production.
	//
	Replace bool // helm (../../../dagger-helm/release.go:350:2)
	//
	// If set, no CRDs will be installed. By default, CRDs are installed if not already present.
	//
	SkipCrds bool // helm (../../../dagger-helm/release.go:363:2)
	//
	// Time to wait for any individual Kubernetes operation (like Jobs for hooks).
	//
	Timeout string // helm (../../../dagger-helm/release.go:368:2)
	//
	// Specify values in a YAML file.
	//
	Values []*File // helm (../../../dagger-helm/release.go:375:2)
	//
	// Verify the package before using it.
	//
	Verify bool // helm (../../../dagger-helm/release.go:380:2)
	//
	// If set, will wait until all Pods, PVCs, Services, and minimum number of Pods of a Deployment, StatefulSet, or ReplicaSet are in a ready state before marking the release as successful. It will wait for as long as timeout.
	//
	Wait bool // helm (../../../dagger-helm/release.go:385:2)
	//
	// If set and wait enabled, will wait until all Jobs have been completed before marking the release as successful. It will wait for as long as timeout.
	//
	WaitForJobs bool // helm (../../../dagger-helm/release.go:390:2)
	//
	// Namespace scope for this request.
	//
	Namespace string // helm (../../../dagger-helm/release.go:397:2)
}

// Install a Helm chart.
func (r *HelmPackage) Install(name string, opts ...HelmPackageInstallOpts) *HelmRelease { // helm (../../../dagger-helm/release.go:232:1)
	q := r.query.Select("install")
	for i := len(opts) - 1; i >= 0; i-- {
		// `atomic` optional argument
		if !querybuilder.IsZeroValue(opts[i].Atomic) {
			q = q.Arg("atomic", opts[i].Atomic)
		}
		// `caFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].CaFile) {
			q = q.Arg("caFile", opts[i].CaFile)
		}
		// `certFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].CertFile) {
			q = q.Arg("certFile", opts[i].CertFile)
		}
		// `createNamespace` optional argument
		if !querybuilder.IsZeroValue(opts[i].CreateNamespace) {
			q = q.Arg("createNamespace", opts[i].CreateNamespace)
		}
		// `dependencyUpdate` optional argument
		if !querybuilder.IsZeroValue(opts[i].DependencyUpdate) {
			q = q.Arg("dependencyUpdate", opts[i].DependencyUpdate)
		}
		// `description` optional argument
		if !querybuilder.IsZeroValue(opts[i].Description) {
			q = q.Arg("description", opts[i].Description)
		}
		// `disableOpenapiValidation` optional argument
		if !querybuilder.IsZeroValue(opts[i].DisableOpenapiValidation) {
			q = q.Arg("disableOpenapiValidation", opts[i].DisableOpenapiValidation)
		}
		// `enableDns` optional argument
		if !querybuilder.IsZeroValue(opts[i].EnableDNS) {
			q = q.Arg("enableDns", opts[i].EnableDNS)
		}
		// `force` optional argument
		if !querybuilder.IsZeroValue(opts[i].Force) {
			q = q.Arg("force", opts[i].Force)
		}
		// `generateName` optional argument
		if !querybuilder.IsZeroValue(opts[i].GenerateName) {
			q = q.Arg("generateName", opts[i].GenerateName)
		}
		// `insecureSkipTlsVerify` optional argument
		if !querybuilder.IsZeroValue(opts[i].InsecureSkipTLSVerify) {
			q = q.Arg("insecureSkipTlsVerify", opts[i].InsecureSkipTLSVerify)
		}
		// `keyFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].KeyFile) {
			q = q.Arg("keyFile", opts[i].KeyFile)
		}
		// `labels` optional argument
		if !querybuilder.IsZeroValue(opts[i].Labels) {
			q = q.Arg("labels", opts[i].Labels)
		}
		// `nameTemplate` optional argument
		if !querybuilder.IsZeroValue(opts[i].NameTemplate) {
			q = q.Arg("nameTemplate", opts[i].NameTemplate)
		}
		// `noHooks` optional argument
		if !querybuilder.IsZeroValue(opts[i].NoHooks) {
			q = q.Arg("noHooks", opts[i].NoHooks)
		}
		// `plainHttp` optional argument
		if !querybuilder.IsZeroValue(opts[i].PlainHTTP) {
			q = q.Arg("plainHttp", opts[i].PlainHTTP)
		}
		// `postRenderer` optional argument
		if !querybuilder.IsZeroValue(opts[i].PostRenderer) {
			q = q.Arg("postRenderer", opts[i].PostRenderer)
		}
		// `postRendererArgs` optional argument
		if !querybuilder.IsZeroValue(opts[i].PostRendererArgs) {
			q = q.Arg("postRendererArgs", opts[i].PostRendererArgs)
		}
		// `renderSubchartNotes` optional argument
		if !querybuilder.IsZeroValue(opts[i].RenderSubchartNotes) {
			q = q.Arg("renderSubchartNotes", opts[i].RenderSubchartNotes)
		}
		// `replace` optional argument
		if !querybuilder.IsZeroValue(opts[i].Replace) {
			q = q.Arg("replace", opts[i].Replace)
		}
		// `skipCrds` optional argument
		if !querybuilder.IsZeroValue(opts[i].SkipCrds) {
			q = q.Arg("skipCrds", opts[i].SkipCrds)
		}
		// `timeout` optional argument
		if !querybuilder.IsZeroValue(opts[i].Timeout) {
			q = q.Arg("timeout", opts[i].Timeout)
		}
		// `values` optional argument
		if !querybuilder.IsZeroValue(opts[i].Values) {
			q = q.Arg("values", opts[i].Values)
		}
		// `verify` optional argument
		if !querybuilder.IsZeroValue(opts[i].Verify) {
			q = q.Arg("verify", opts[i].Verify)
		}
		// `wait` optional argument
		if !querybuilder.IsZeroValue(opts[i].Wait) {
			q = q.Arg("wait", opts[i].Wait)
		}
		// `waitForJobs` optional argument
		if !querybuilder.IsZeroValue(opts[i].WaitForJobs) {
			q = q.Arg("waitForJobs", opts[i].WaitForJobs)
		}
		// `namespace` optional argument
		if !querybuilder.IsZeroValue(opts[i].Namespace) {
			q = q.Arg("namespace", opts[i].Namespace)
		}
	}
	q = q.Arg("name", name)

	return &HelmRelease{
		query: q,
	}
}

// HelmPackagePublishOpts contains options for HelmPackage.Publish
type HelmPackagePublishOpts struct {
	//
	// Use insecure HTTP connections for the chart upload.
	//
	PlainHTTP bool // helm (../../../dagger-helm/chart.go:112:2)
	//
	// Skip tls certificate checks for the chart upload.
	//
	InsecureSkipTLSVerify bool // helm (../../../dagger-helm/chart.go:117:2)
	//
	// Verify certificates of HTTPS-enabled servers using this CA bundle.
	//
	CaFile *File // helm (../../../dagger-helm/chart.go:122:2)
	//
	// Identify registry client using this SSL certificate file.
	//
	CertFile *File // helm (../../../dagger-helm/chart.go:127:2)
	//
	// Identify registry client using this SSL key file.
	//
	KeyFile *Secret // helm (../../../dagger-helm/chart.go:132:2)
}

// Publishes this Helm chart package to an OCI registry.
func (r *HelmPackage) Publish(ctx context.Context, registry string, opts ...HelmPackagePublishOpts) error { // helm (../../../dagger-helm/chart.go:103:1)
	if r.publish != nil {
		return nil
	}
	q := r.query.Select("publish")
	for i := len(opts) - 1; i >= 0; i-- {
		// `plainHttp` optional argument
		if !querybuilder.IsZeroValue(opts[i].PlainHTTP) {
			q = q.Arg("plainHttp", opts[i].PlainHTTP)
		}
		// `insecureSkipTlsVerify` optional argument
		if !querybuilder.IsZeroValue(opts[i].InsecureSkipTLSVerify) {
			q = q.Arg("insecureSkipTlsVerify", opts[i].InsecureSkipTLSVerify)
		}
		// `caFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].CaFile) {
			q = q.Arg("caFile", opts[i].CaFile)
		}
		// `certFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].CertFile) {
			q = q.Arg("certFile", opts[i].CertFile)
		}
		// `keyFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].KeyFile) {
			q = q.Arg("keyFile", opts[i].KeyFile)
		}
	}
	q = q.Arg("registry", registry)

	return q.Execute(ctx)
}

// Mount a file as the kubeconfig file.
func (r *HelmPackage) WithKubeconfigFile(file *File) *HelmPackage { // helm (../../../dagger-helm/chart.go:89:1)
	assertNotNil("file", file)
	q := r.query.Select("withKubeconfigFile")
	q = q.Arg("file", file)

	return &HelmPackage{
		query: q,
	}
}

// Mount a secret as the kubeconfig file.
func (r *HelmPackage) WithKubeconfigSecret(secret *Secret) *HelmPackage { // helm (../../../dagger-helm/chart.go:96:1)
	assertNotNil("secret", secret)
	q := r.query.Select("withKubeconfigSecret")
	q = q.Arg("secret", secret)

	return &HelmPackage{
		query: q,
	}
}

// Add credentials for a registry.
func (r *HelmPackage) WithRegistryAuth(address string, username string, secret *Secret) *HelmPackage { // helm (../../../dagger-helm/chart.go:75:1)
	assertNotNil("secret", secret)
	q := r.query.Select("withRegistryAuth")
	q = q.Arg("address", address)
	q = q.Arg("username", username)
	q = q.Arg("secret", secret)

	return &HelmPackage{
		query: q,
	}
}

// Removes credentials for a registry.
func (r *HelmPackage) WithoutRegistryAuth(address string) *HelmPackage { // helm (../../../dagger-helm/chart.go:82:1)
	q := r.query.Select("withoutRegistryAuth")
	q = q.Arg("address", address)

	return &HelmPackage{
		query: q,
	}
}

type HelmRelease struct { // helm (../../../dagger-helm/release.go:637:6)
	query *querybuilder.Selection

	id        *HelmReleaseID
	name      *string
	namespace *string
	test      *string
}

func (r *HelmRelease) WithGraphQLQuery(q *querybuilder.Selection) *HelmRelease {
	return &HelmRelease{
		query: q,
	}
}

// A unique identifier for this HelmRelease.
func (r *HelmRelease) ID(ctx context.Context) (HelmReleaseID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response HelmReleaseID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *HelmRelease) XXX_GraphQLType() string {
	return "HelmRelease"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *HelmRelease) XXX_GraphQLIDType() string {
	return "HelmReleaseID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *HelmRelease) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *HelmRelease) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *HelmRelease) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = *dag.LoadHelmReleaseFromID(HelmReleaseID(id))
	return nil
}

func (r *HelmRelease) Name(ctx context.Context) (string, error) { // helm (../../../dagger-helm/release.go:638:2)
	if r.name != nil {
		return *r.name, nil
	}
	q := r.query.Select("name")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *HelmRelease) Namespace(ctx context.Context) (string, error) { // helm (../../../dagger-helm/release.go:639:2)
	if r.namespace != nil {
		return *r.namespace, nil
	}
	q := r.query.Select("namespace")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// HelmReleaseTestOpts contains options for HelmRelease.Test
type HelmReleaseTestOpts struct {
	//
	// Specify tests by attribute (currently "name") using attribute=value syntax or '!attribute=value' to exclude a test.
	//
	Filter []string // helm (../../../dagger-helm/release.go:652:2)
	//
	// Dump the logs from test pods (this runs after all tests are complete, but before any cleanup).
	//
	Logs bool // helm (../../../dagger-helm/release.go:657:2)
	//
	// Time to wait for any individual Kubernetes operation (like Jobs for hooks) (default 5m0s).
	//
	Timeout string // helm (../../../dagger-helm/release.go:662:2)
}

// Run Helm tests.
func (r *HelmRelease) Test(ctx context.Context, opts ...HelmReleaseTestOpts) (string, error) { // helm (../../../dagger-helm/release.go:646:1)
	if r.test != nil {
		return *r.test, nil
	}
	q := r.query.Select("test")
	for i := len(opts) - 1; i >= 0; i-- {
		// `filter` optional argument
		if !querybuilder.IsZeroValue(opts[i].Filter) {
			q = q.Arg("filter", opts[i].Filter)
		}
		// `logs` optional argument
		if !querybuilder.IsZeroValue(opts[i].Logs) {
			q = q.Arg("logs", opts[i].Logs)
		}
		// `timeout` optional argument
		if !querybuilder.IsZeroValue(opts[i].Timeout) {
			q = q.Arg("timeout", opts[i].Timeout)
		}
	}

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// HelmOpts contains options for Query.Helm
type HelmOpts struct {
	//
	// Version (image tag) to use from the official image repository as a base container.
	//
	Version string // helm (../../../dagger-helm/main.go:27:2)
	//
	// Custom container to use as a base container.
	//
	Container *Container // helm (../../../dagger-helm/main.go:31:2)
}

// The package manager for Kubernetes.
func (r *Query) Helm(opts ...HelmOpts) *Helm { // helm (../../../dagger-helm/main.go:24:1)
	q := r.query.Select("helm")
	for i := len(opts) - 1; i >= 0; i-- {
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
		// `container` optional argument
		if !querybuilder.IsZeroValue(opts[i].Container) {
			q = q.Arg("container", opts[i].Container)
		}
	}

	return &Helm{
		query: q,
	}
}

// Load a HelmChart from its ID.
func (r *Query) LoadHelmChartFromID(id HelmChartID) *HelmChart { // helm (../../../dagger-helm/chart.go:20:6)
	q := r.query.Select("loadHelmChartFromID")
	q = q.Arg("id", id)

	return &HelmChart{
		query: q,
	}
}

// Load a Helm from its ID.
func (r *Query) LoadHelmFromID(id HelmID) *Helm { // helm (../../../dagger-helm/main.go:17:6)
	q := r.query.Select("loadHelmFromID")
	q = q.Arg("id", id)

	return &Helm{
		query: q,
	}
}

// Load a HelmPackage from its ID.
func (r *Query) LoadHelmPackageFromID(id HelmPackageID) *HelmPackage { // helm (../../../dagger-helm/chart.go:33:6)
	q := r.query.Select("loadHelmPackageFromID")
	q = q.Arg("id", id)

	return &HelmPackage{
		query: q,
	}
}

// Load a HelmRelease from its ID.
func (r *Query) LoadHelmReleaseFromID(id HelmReleaseID) *HelmRelease { // helm (../../../dagger-helm/release.go:637:6)
	q := r.query.Select("loadHelmReleaseFromID")
	q = q.Arg("id", id)

	return &HelmRelease{
		query: q,
	}
}
