// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package gensql

import (
	"context"
)

const createIngredient = `-- name: CreateIngredient :one
INSERT INTO ingredients (name, ingredient_category_id) VALUES (?, ?) RETURNING id
`

type CreateIngredientParams struct {
	Name                 string
	IngredientCategoryID int64
}

func (q *Queries) CreateIngredient(ctx context.Context, arg CreateIngredientParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createIngredient, arg.Name, arg.IngredientCategoryID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createIngredientCategory = `-- name: CreateIngredientCategory :one
INSERT INTO ingredient_categories (name, sort_index) VALUES (
    ?, 
    (COALESCE((SELECT sort_index FROM ingredient_categories ORDER BY sort_index DESC LIMIT 1), 0) + 1)
) RETURNING id, sort_index
`

type CreateIngredientCategoryRow struct {
	ID        int64
	SortIndex int64
}

func (q *Queries) CreateIngredientCategory(ctx context.Context, name string) (CreateIngredientCategoryRow, error) {
	row := q.db.QueryRowContext(ctx, createIngredientCategory, name)
	var i CreateIngredientCategoryRow
	err := row.Scan(&i.ID, &i.SortIndex)
	return i, err
}

const createMeal = `-- name: CreateMeal :one
INSERT INTO meals (
 name,
 ingredients,
 recipe_url,
 preview_image_mode,
 preview_image_url,
 ingredients_image_mode,
 ingredients_image_url
) VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id
`

type CreateMealParams struct {
	Name                 string
	Ingredients          string
	RecipeUrl            string
	PreviewImageMode     interface{}
	PreviewImageUrl      interface{}
	IngredientsImageMode interface{}
	IngredientsImageUrl  interface{}
}

func (q *Queries) CreateMeal(ctx context.Context, arg CreateMealParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createMeal,
		arg.Name,
		arg.Ingredients,
		arg.RecipeUrl,
		arg.PreviewImageMode,
		arg.PreviewImageUrl,
		arg.IngredientsImageMode,
		arg.IngredientsImageUrl,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createPlan = `-- name: CreatePlan :exec
INSERT INTO plan (plan_data) VALUES (?)
`

func (q *Queries) CreatePlan(ctx context.Context, planData string) error {
	_, err := q.db.ExecContext(ctx, createPlan, planData)
	return err
}

const deleteIngredient = `-- name: DeleteIngredient :exec
DELETE FROM ingredients WHERE id = ?
`

func (q *Queries) DeleteIngredient(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteIngredient, id)
	return err
}

const deleteIngredientCategory = `-- name: DeleteIngredientCategory :exec
DELETE FROM ingredient_categories WHERE id = ?
`

func (q *Queries) DeleteIngredientCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteIngredientCategory, id)
	return err
}

const deleteMeal = `-- name: DeleteMeal :exec
DELETE FROM meals WHERE id = ?
`

func (q *Queries) DeleteMeal(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMeal, id)
	return err
}

const getIngredientCategories = `-- name: GetIngredientCategories :many

SELECT id, name, sort_index FROM ingredient_categories
ORDER BY sort_index ASC
`

// ----- INGREDIENT CATEGORIES ------
func (q *Queries) GetIngredientCategories(ctx context.Context) ([]IngredientCategory, error) {
	rows, err := q.db.QueryContext(ctx, getIngredientCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngredientCategory
	for rows.Next() {
		var i IngredientCategory
		if err := rows.Scan(&i.ID, &i.Name, &i.SortIndex); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIngredientCategorySortIndex = `-- name: GetIngredientCategorySortIndex :one
SELECT sort_index FROM ingredient_categories WHERE id = ?
`

func (q *Queries) GetIngredientCategorySortIndex(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getIngredientCategorySortIndex, id)
	var sort_index int64
	err := row.Scan(&sort_index)
	return sort_index, err
}

const getIngredients = `-- name: GetIngredients :many

SELECT id, name, ingredient_category_id, want_override_count, min_count, max_count, got_count, shopped FROM ingredients
ORDER BY name
`

type GetIngredientsRow struct {
	ID                   int64
	Name                 string
	IngredientCategoryID int64
	WantOverrideCount    int64
	MinCount             int64
	MaxCount             int64
	GotCount             int64
	Shopped              bool
}

// ----- INGREDIENTS ------
func (q *Queries) GetIngredients(ctx context.Context) ([]GetIngredientsRow, error) {
	rows, err := q.db.QueryContext(ctx, getIngredients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIngredientsRow
	for rows.Next() {
		var i GetIngredientsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IngredientCategoryID,
			&i.WantOverrideCount,
			&i.MinCount,
			&i.MaxCount,
			&i.GotCount,
			&i.Shopped,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMealIngredientsImageBytes = `-- name: GetMealIngredientsImageBytes :one
SELECT ingredients_image_bytes FROM meals WHERE id = ?
`

func (q *Queries) GetMealIngredientsImageBytes(ctx context.Context, id int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMealIngredientsImageBytes, id)
	var ingredients_image_bytes interface{}
	err := row.Scan(&ingredients_image_bytes)
	return ingredients_image_bytes, err
}

const getMealPreviewImageBytes = `-- name: GetMealPreviewImageBytes :one
SELECT preview_image_bytes FROM meals WHERE id = ?
`

func (q *Queries) GetMealPreviewImageBytes(ctx context.Context, id int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMealPreviewImageBytes, id)
	var preview_image_bytes interface{}
	err := row.Scan(&preview_image_bytes)
	return preview_image_bytes, err
}

const getMeals = `-- name: GetMeals :many

SELECT 
    id, 
    name, 
    ingredients, 
    recipe_url, 
    preview_image_mode,
    preview_image_url,
    ingredients_image_mode,
    ingredients_image_url
FROM meals
ORDER BY name
`

type GetMealsRow struct {
	ID                   int64
	Name                 string
	Ingredients          string
	RecipeUrl            string
	PreviewImageMode     interface{}
	PreviewImageUrl      interface{}
	IngredientsImageMode interface{}
	IngredientsImageUrl  interface{}
}

// ----- MEALS ------
func (q *Queries) GetMeals(ctx context.Context) ([]GetMealsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMeals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMealsRow
	for rows.Next() {
		var i GetMealsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Ingredients,
			&i.RecipeUrl,
			&i.PreviewImageMode,
			&i.PreviewImageUrl,
			&i.IngredientsImageMode,
			&i.IngredientsImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlan = `-- name: GetPlan :one

SELECT id, plan_data FROM plan LIMIT 1
`

// ----- PLAN --------
func (q *Queries) GetPlan(ctx context.Context) (Plan, error) {
	row := q.db.QueryRowContext(ctx, getPlan)
	var i Plan
	err := row.Scan(&i.ID, &i.PlanData)
	return i, err
}

const resetIngredientGotCount = `-- name: ResetIngredientGotCount :exec
UPDATE ingredients SET got_count = 0
`

func (q *Queries) ResetIngredientGotCount(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetIngredientGotCount)
	return err
}

const resetIngredientShopped = `-- name: ResetIngredientShopped :exec
UPDATE ingredients SET shopped = FALSE
`

func (q *Queries) ResetIngredientShopped(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetIngredientShopped)
	return err
}

const updateIngredient = `-- name: UpdateIngredient :exec
UPDATE ingredients set name = ?, ingredient_category_id = ? WHERE id = ?
`

type UpdateIngredientParams struct {
	Name                 string
	IngredientCategoryID int64
	ID                   int64
}

func (q *Queries) UpdateIngredient(ctx context.Context, arg UpdateIngredientParams) error {
	_, err := q.db.ExecContext(ctx, updateIngredient, arg.Name, arg.IngredientCategoryID, arg.ID)
	return err
}

const updateIngredientCategory = `-- name: UpdateIngredientCategory :exec
UPDATE ingredient_categories SET name = ? WHERE id = ?
`

type UpdateIngredientCategoryParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdateIngredientCategory(ctx context.Context, arg UpdateIngredientCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateIngredientCategory, arg.Name, arg.ID)
	return err
}

const updateIngredientCategorySortIndex = `-- name: UpdateIngredientCategorySortIndex :exec
UPDATE ingredient_categories SET sort_index = ? WHERE id = ?
`

type UpdateIngredientCategorySortIndexParams struct {
	SortIndex int64
	ID        int64
}

func (q *Queries) UpdateIngredientCategorySortIndex(ctx context.Context, arg UpdateIngredientCategorySortIndexParams) error {
	_, err := q.db.ExecContext(ctx, updateIngredientCategorySortIndex, arg.SortIndex, arg.ID)
	return err
}

const updateIngredientCounts = `-- name: UpdateIngredientCounts :exec
UPDATE ingredients set min_count = ?, max_count = ?, want_override_count = ? WHERE id = ?
`

type UpdateIngredientCountsParams struct {
	MinCount          int64
	MaxCount          int64
	WantOverrideCount int64
	ID                int64
}

func (q *Queries) UpdateIngredientCounts(ctx context.Context, arg UpdateIngredientCountsParams) error {
	_, err := q.db.ExecContext(ctx, updateIngredientCounts,
		arg.MinCount,
		arg.MaxCount,
		arg.WantOverrideCount,
		arg.ID,
	)
	return err
}

const updateIngredientGotCount = `-- name: UpdateIngredientGotCount :exec
UPDATE ingredients SET got_count = ? WHERE id = ?
`

type UpdateIngredientGotCountParams struct {
	GotCount int64
	ID       int64
}

func (q *Queries) UpdateIngredientGotCount(ctx context.Context, arg UpdateIngredientGotCountParams) error {
	_, err := q.db.ExecContext(ctx, updateIngredientGotCount, arg.GotCount, arg.ID)
	return err
}

const updateIngredientShopped = `-- name: UpdateIngredientShopped :exec
UPDATE ingredients SET shopped = ? WHERE id = ?
`

type UpdateIngredientShoppedParams struct {
	Shopped bool
	ID      int64
}

func (q *Queries) UpdateIngredientShopped(ctx context.Context, arg UpdateIngredientShoppedParams) error {
	_, err := q.db.ExecContext(ctx, updateIngredientShopped, arg.Shopped, arg.ID)
	return err
}

const updateMeal = `-- name: UpdateMeal :exec
UPDATE meals set name = ?,
 ingredients = ?,
 recipe_url = ?,
 preview_image_mode = ?,
 preview_image_url = ?,
 ingredients_image_mode = ?,
 ingredients_image_url = ?
WHERE id = ?
`

type UpdateMealParams struct {
	Name                 string
	Ingredients          string
	RecipeUrl            string
	PreviewImageMode     interface{}
	PreviewImageUrl      interface{}
	IngredientsImageMode interface{}
	IngredientsImageUrl  interface{}
	ID                   int64
}

func (q *Queries) UpdateMeal(ctx context.Context, arg UpdateMealParams) error {
	_, err := q.db.ExecContext(ctx, updateMeal,
		arg.Name,
		arg.Ingredients,
		arg.RecipeUrl,
		arg.PreviewImageMode,
		arg.PreviewImageUrl,
		arg.IngredientsImageMode,
		arg.IngredientsImageUrl,
		arg.ID,
	)
	return err
}

const updateMealIngredientsImageBytes = `-- name: UpdateMealIngredientsImageBytes :exec
UPDATE meals set ingredients_image_bytes = ? WHERE id = ?
`

type UpdateMealIngredientsImageBytesParams struct {
	IngredientsImageBytes interface{}
	ID                    int64
}

func (q *Queries) UpdateMealIngredientsImageBytes(ctx context.Context, arg UpdateMealIngredientsImageBytesParams) error {
	_, err := q.db.ExecContext(ctx, updateMealIngredientsImageBytes, arg.IngredientsImageBytes, arg.ID)
	return err
}

const updateMealPreviewImageBytes = `-- name: UpdateMealPreviewImageBytes :exec
UPDATE meals set preview_image_bytes = ? WHERE id = ?
`

type UpdateMealPreviewImageBytesParams struct {
	PreviewImageBytes interface{}
	ID                int64
}

func (q *Queries) UpdateMealPreviewImageBytes(ctx context.Context, arg UpdateMealPreviewImageBytesParams) error {
	_, err := q.db.ExecContext(ctx, updateMealPreviewImageBytes, arg.PreviewImageBytes, arg.ID)
	return err
}

const updatePlan = `-- name: UpdatePlan :exec
UPDATE plan set plan_data = ? WHERE id = ?
`

type UpdatePlanParams struct {
	PlanData string
	ID       int64
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) error {
	_, err := q.db.ExecContext(ctx, updatePlan, arg.PlanData, arg.ID)
	return err
}
