// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

func (r *Query) Unittests(ws *Workspace) *Unittests { // unittests (../../../../../:0:0)
	assertNotNil("ws", ws)
	q := r.query.Select("unittests")
	q = q.Arg("ws", ws)

	return &Unittests{
		query: q,
	}
}

type Unittests struct { // unittests (../../../../../:0:0)
	query *querybuilder.Selection

	id *ID
}
type WithUnittestsFunc func(r *Unittests) *Unittests

// With calls the provided function with current Unittests.
//
// This is useful for reusability and readability by not breaking the calling chain.
func (r *Unittests) With(f WithUnittestsFunc) *Unittests {
	return f(r)
}

func (r *Unittests) WithGraphQLQuery(q *querybuilder.Selection) *Unittests {
	return &Unittests{
		query: q,
	}
}

func (r *Unittests) Get(key string) *UnittestsPackage {
	q := r.query.Select("get")
	q = q.Arg("key", key)

	return &UnittestsPackage{
		query: q,
	}
}

// A unique identifier for this Unittests.
func (r *Unittests) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Unittests) XXX_GraphQLType() string {
	return "Unittests"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Unittests) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Unittests) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Unittests) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Unittests) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Unittests{query: selectNode(dag.query, id, "Unittests")}
	return nil
}

func (r *Unittests) Keys(ctx context.Context) ([]string, error) {
	q := r.query.Select("keys")

	var response []string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *Unittests) List(ctx context.Context) ([]UnittestsPackage, error) {
	q := r.query.Select("list")

	q = q.Select("id")

	type list struct {
		Id ID
	}

	convert := func(fields []list) []UnittestsPackage {
		out := []UnittestsPackage{}

		for i := range fields {
			val := UnittestsPackage{id: &fields[i].Id}
			val.query = selectNode(q.Root(), fields[i].Id, "UnittestsPackage")
			out = append(out, val)
		}

		return out
	}
	var response []list

	q = q.Bind(&response)

	err := q.Execute(ctx)
	if err != nil {
		return nil, err
	}

	return convert(response), nil
}

func (r *Unittests) Subset(keys []string) *Unittests {
	q := r.query.Select("subset")
	q = q.Arg("keys", keys)

	return &Unittests{
		query: q,
	}
}

type UnittestsPackage struct { // unittests (../../../../../:0:0)
	query *querybuilder.Selection

	id   *ID
	path *string
	test *Void
}

func (r *UnittestsPackage) WithGraphQLQuery(q *querybuilder.Selection) *UnittestsPackage {
	return &UnittestsPackage{
		query: q,
	}
}

// A unique identifier for this UnittestsPackage.
func (r *UnittestsPackage) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *UnittestsPackage) XXX_GraphQLType() string {
	return "UnittestsPackage"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *UnittestsPackage) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *UnittestsPackage) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *UnittestsPackage) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *UnittestsPackage) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = UnittestsPackage{query: selectNode(dag.query, id, "UnittestsPackage")}
	return nil
}

func (r *UnittestsPackage) Path(ctx context.Context) (string, error) {
	if r.path != nil {
		return *r.path, nil
	}
	q := r.query.Select("path")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *UnittestsPackage) Test(ctx context.Context, ws *Workspace) error {
	assertNotNil("ws", ws)
	if r.test != nil {
		return nil
	}
	q := r.query.Select("test")
	q = q.Arg("ws", ws)

	return q.Execute(ctx)
}
