// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

type MigrationTools struct { // migration-tools (../../../../../../:0:0)
	query *querybuilder.Selection

	checkMigrationValid       *Void
	id                        *ID
	testMigrationToolsNodb    *Void
	testMigrationToolsNodbenv *Void
	testMigrationToolsWithDb  *Void
}

func (r *MigrationTools) WithGraphQLQuery(q *querybuilder.Selection) *MigrationTools {
	return &MigrationTools{
		query: q,
	}
}

// CheckMigrationValid - checks whether a migration from the previous schema to the new schema succeeds.
func (r *MigrationTools) CheckMigrationValid(ctx context.Context, prevSchemaSql *File, newSchemaSql *File) error {
	assertNotNil("prevSchemaSql", prevSchemaSql)
	assertNotNil("newSchemaSql", newSchemaSql)
	if r.checkMigrationValid != nil {
		return nil
	}
	q := r.query.Select("checkMigrationValid")
	q = q.Arg("prevSchemaSql", prevSchemaSql)
	q = q.Arg("newSchemaSql", newSchemaSql)

	return q.Execute(ctx)
}

// A unique identifier for this MigrationTools.
func (r *MigrationTools) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *MigrationTools) XXX_GraphQLType() string {
	return "MigrationTools"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *MigrationTools) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *MigrationTools) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *MigrationTools) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *MigrationTools) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = MigrationTools{query: selectNode(dag.query, id, "MigrationTools")}
	return nil
}

// InstallMigrationTools - installs the migration tools into the specified container
func (r *MigrationTools) InstallMigrationTools(ctr *Container) *Container {
	assertNotNil("ctr", ctr)
	q := r.query.Select("installMigrationTools")
	q = q.Arg("ctr", ctr)

	return &Container{
		query: q,
	}
}

// MigrateDatabase - migrates the passed in database, to the provided schema and returns it
func (r *MigrationTools) MigrateDatabase(db *File, schemaSql *File) *File {
	assertNotNil("db", db)
	assertNotNil("schemaSql", schemaSql)
	q := r.query.Select("migrateDatabase")
	q = q.Arg("db", db)
	q = q.Arg("schemaSql", schemaSql)

	return &File{
		query: q,
	}
}

// MountSchemaSQL - installs the migration sql into the expected location
func (r *MigrationTools) MountSchemaSQL(ctr *Container, schemaSql *File) *Container {
	assertNotNil("ctr", ctr)
	assertNotNil("schemaSql", schemaSql)
	q := r.query.Select("mountSchemaSql")
	q = q.Arg("ctr", ctr)
	q = q.Arg("schemaSql", schemaSql)

	return &Container{
		query: q,
	}
}

// TestMigrationToolsNODB - tests that the migration tools work if the DB doesn't exist
func (r *MigrationTools) TestMigrationToolsNodb(ctx context.Context) error {
	if r.testMigrationToolsNodb != nil {
		return nil
	}
	q := r.query.Select("testMigrationToolsNodb")

	return q.Execute(ctx)
}

// TestMigrationToolsNoDBEnv - tests that the migration tools correctly fail if the DATABASE_FILE var isn't present
func (r *MigrationTools) TestMigrationToolsNodbenv(ctx context.Context) error {
	if r.testMigrationToolsNodbenv != nil {
		return nil
	}
	q := r.query.Select("testMigrationToolsNodbenv")

	return q.Execute(ctx)
}

// TestMigrationToolsWithDB - tests that the migration tools work if the DB exists
func (r *MigrationTools) TestMigrationToolsWithDb(ctx context.Context) error {
	if r.testMigrationToolsWithDb != nil {
		return nil
	}
	q := r.query.Select("testMigrationToolsWithDb")

	return q.Execute(ctx)
}

func (r *Query) MigrationTools() *MigrationTools { // migration-tools (../../../../../../:0:0)
	q := r.query.Select("migrationTools")

	return &MigrationTools{
		query: q,
	}
}
