// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"dagger/helm/internal/dagger"

	"github.com/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject interface {
	querybuilder.GraphQLMarshaller
	ID(ctx context.Context) (dagger.ID, error)
}

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r Helm) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Container      *dagger.Container
		RegistryConfig *dagger.RegistryConfig
	}
	concrete.Container = r.Container
	concrete.RegistryConfig = r.RegistryConfig
	return json.Marshal(&concrete)
}

func (r *Helm) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Container      *dagger.Container
		RegistryConfig *dagger.RegistryConfig
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Container = concrete.Container
	r.RegistryConfig = concrete.RegistryConfig
	return nil
}

func (r Chart) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Directory *dagger.Directory
		Helm      *Helm
	}
	concrete.Directory = r.Directory
	concrete.Helm = r.Helm
	return json.Marshal(&concrete)
}

func (r *Chart) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Directory *dagger.Directory
		Helm      *Helm
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Directory = concrete.Directory
	r.Helm = concrete.Helm
	return nil
}

func (r Release) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Name      string
		Namespace string
		Container *dagger.Container
	}
	concrete.Name = r.Name
	concrete.Namespace = r.Namespace
	concrete.Container = r.Container
	return json.Marshal(&concrete)
}

func (r *Release) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Name      string
		Namespace string
		Container *dagger.Container
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Name = concrete.Name
	r.Namespace = concrete.Namespace
	r.Container = concrete.Container
	return nil
}

func (r Package) MarshalJSON() ([]byte, error) {
	var concrete struct {
		File  *dagger.File
		Helm  *Helm
		Chart *Chart
	}
	concrete.File = r.File
	concrete.Helm = r.Helm
	concrete.Chart = r.Chart
	return json.Marshal(&concrete)
}

func (r *Package) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		File  *dagger.File
		Helm  *Helm
		Chart *Chart
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.File = concrete.File
	r.Helm = concrete.Helm
	r.Chart = concrete.Chart
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "Chart":
		switch fnName {
		case "Install":
			var parent Chart
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var name string
			if inputArgs["name"] != nil {
				err = json.Unmarshal([]byte(inputArgs["name"]), &name)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg name", err))
				}
			}
			var atomic bool
			if inputArgs["atomic"] != nil {
				err = json.Unmarshal([]byte(inputArgs["atomic"]), &atomic)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg atomic", err))
				}
			}
			var caFile *dagger.File
			if inputArgs["caFile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["caFile"]), &caFile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg caFile", err))
				}
			}
			var certFile *dagger.File
			if inputArgs["certFile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["certFile"]), &certFile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg certFile", err))
				}
			}
			var createNamespace bool
			if inputArgs["createNamespace"] != nil {
				err = json.Unmarshal([]byte(inputArgs["createNamespace"]), &createNamespace)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg createNamespace", err))
				}
			}
			var dependencyUpdate bool
			if inputArgs["dependencyUpdate"] != nil {
				err = json.Unmarshal([]byte(inputArgs["dependencyUpdate"]), &dependencyUpdate)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg dependencyUpdate", err))
				}
			}
			var description string
			if inputArgs["description"] != nil {
				err = json.Unmarshal([]byte(inputArgs["description"]), &description)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg description", err))
				}
			}
			var disableOpenapiValidation bool
			if inputArgs["disableOpenapiValidation"] != nil {
				err = json.Unmarshal([]byte(inputArgs["disableOpenapiValidation"]), &disableOpenapiValidation)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg disableOpenapiValidation", err))
				}
			}
			var enableDns bool
			if inputArgs["enableDns"] != nil {
				err = json.Unmarshal([]byte(inputArgs["enableDns"]), &enableDns)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg enableDns", err))
				}
			}
			var force bool
			if inputArgs["force"] != nil {
				err = json.Unmarshal([]byte(inputArgs["force"]), &force)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg force", err))
				}
			}
			var generateName bool
			if inputArgs["generateName"] != nil {
				err = json.Unmarshal([]byte(inputArgs["generateName"]), &generateName)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg generateName", err))
				}
			}
			var insecureSkipTlsVerify bool
			if inputArgs["insecureSkipTlsVerify"] != nil {
				err = json.Unmarshal([]byte(inputArgs["insecureSkipTlsVerify"]), &insecureSkipTlsVerify)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg insecureSkipTlsVerify", err))
				}
			}
			var keyFile *dagger.Secret
			if inputArgs["keyFile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["keyFile"]), &keyFile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg keyFile", err))
				}
			}
			var labels []string
			if inputArgs["labels"] != nil {
				err = json.Unmarshal([]byte(inputArgs["labels"]), &labels)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg labels", err))
				}
			}
			var nameTemplate string
			if inputArgs["nameTemplate"] != nil {
				err = json.Unmarshal([]byte(inputArgs["nameTemplate"]), &nameTemplate)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg nameTemplate", err))
				}
			}
			var noHooks bool
			if inputArgs["noHooks"] != nil {
				err = json.Unmarshal([]byte(inputArgs["noHooks"]), &noHooks)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg noHooks", err))
				}
			}
			var plainHttp bool
			if inputArgs["plainHttp"] != nil {
				err = json.Unmarshal([]byte(inputArgs["plainHttp"]), &plainHttp)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg plainHttp", err))
				}
			}
			var postRenderer string
			if inputArgs["postRenderer"] != nil {
				err = json.Unmarshal([]byte(inputArgs["postRenderer"]), &postRenderer)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg postRenderer", err))
				}
			}
			var postRendererArgs []string
			if inputArgs["postRendererArgs"] != nil {
				err = json.Unmarshal([]byte(inputArgs["postRendererArgs"]), &postRendererArgs)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg postRendererArgs", err))
				}
			}
			var renderSubchartNotes bool
			if inputArgs["renderSubchartNotes"] != nil {
				err = json.Unmarshal([]byte(inputArgs["renderSubchartNotes"]), &renderSubchartNotes)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg renderSubchartNotes", err))
				}
			}
			var replace bool
			if inputArgs["replace"] != nil {
				err = json.Unmarshal([]byte(inputArgs["replace"]), &replace)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg replace", err))
				}
			}
			var skipCrds bool
			if inputArgs["skipCrds"] != nil {
				err = json.Unmarshal([]byte(inputArgs["skipCrds"]), &skipCrds)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg skipCrds", err))
				}
			}
			var timeout string
			if inputArgs["timeout"] != nil {
				err = json.Unmarshal([]byte(inputArgs["timeout"]), &timeout)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg timeout", err))
				}
			}
			var values []*dagger.File
			if inputArgs["values"] != nil {
				err = json.Unmarshal([]byte(inputArgs["values"]), &values)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg values", err))
				}
			}
			var verify bool
			if inputArgs["verify"] != nil {
				err = json.Unmarshal([]byte(inputArgs["verify"]), &verify)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg verify", err))
				}
			}
			var wait bool
			if inputArgs["wait"] != nil {
				err = json.Unmarshal([]byte(inputArgs["wait"]), &wait)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg wait", err))
				}
			}
			var waitForJobs bool
			if inputArgs["waitForJobs"] != nil {
				err = json.Unmarshal([]byte(inputArgs["waitForJobs"]), &waitForJobs)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg waitForJobs", err))
				}
			}
			var namespace string
			if inputArgs["namespace"] != nil {
				err = json.Unmarshal([]byte(inputArgs["namespace"]), &namespace)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg namespace", err))
				}
			}
			return (*Chart).Install(&parent, ctx, name, atomic, caFile, certFile, createNamespace, dependencyUpdate, description, disableOpenapiValidation, enableDns, force, generateName, insecureSkipTlsVerify, keyFile, labels, nameTemplate, noHooks, plainHttp, postRenderer, postRendererArgs, renderSubchartNotes, replace, skipCrds, timeout, values, verify, wait, waitForJobs, namespace)
		case "Lint":
			var parent Chart
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Chart).Lint(&parent, ctx)
		case "Package":
			var parent Chart
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var appVersion string
			if inputArgs["appVersion"] != nil {
				err = json.Unmarshal([]byte(inputArgs["appVersion"]), &appVersion)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg appVersion", err))
				}
			}
			var version string
			if inputArgs["version"] != nil {
				err = json.Unmarshal([]byte(inputArgs["version"]), &version)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg version", err))
				}
			}
			var dependencyUpdate bool
			if inputArgs["dependencyUpdate"] != nil {
				err = json.Unmarshal([]byte(inputArgs["dependencyUpdate"]), &dependencyUpdate)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg dependencyUpdate", err))
				}
			}
			return (*Chart).Package(&parent, ctx, appVersion, version, dependencyUpdate)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "Helm":
		switch fnName {
		case "Chart":
			var parent Helm
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*Helm).Chart(&parent, source), nil
		case "Create":
			var parent Helm
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var name string
			if inputArgs["name"] != nil {
				err = json.Unmarshal([]byte(inputArgs["name"]), &name)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg name", err))
				}
			}
			return (*Helm).Create(&parent, name), nil
		case "Lint":
			var parent Helm
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var chart *dagger.Directory
			if inputArgs["chart"] != nil {
				err = json.Unmarshal([]byte(inputArgs["chart"]), &chart)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg chart", err))
				}
			}
			return (*Helm).Lint(&parent, ctx, chart)
		case "Login":
			var parent Helm
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var host string
			if inputArgs["host"] != nil {
				err = json.Unmarshal([]byte(inputArgs["host"]), &host)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg host", err))
				}
			}
			var username string
			if inputArgs["username"] != nil {
				err = json.Unmarshal([]byte(inputArgs["username"]), &username)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg username", err))
				}
			}
			var password *dagger.Secret
			if inputArgs["password"] != nil {
				err = json.Unmarshal([]byte(inputArgs["password"]), &password)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg password", err))
				}
			}
			var insecure bool
			if inputArgs["insecure"] != nil {
				err = json.Unmarshal([]byte(inputArgs["insecure"]), &insecure)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg insecure", err))
				}
			}
			return (*Helm).Login(&parent, ctx, host, username, password, insecure), nil
		case "Logout":
			var parent Helm
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var host string
			if inputArgs["host"] != nil {
				err = json.Unmarshal([]byte(inputArgs["host"]), &host)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg host", err))
				}
			}
			return (*Helm).Logout(&parent, host), nil
		case "Package":
			var parent Helm
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var chart *dagger.Directory
			if inputArgs["chart"] != nil {
				err = json.Unmarshal([]byte(inputArgs["chart"]), &chart)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg chart", err))
				}
			}
			var appVersion string
			if inputArgs["appVersion"] != nil {
				err = json.Unmarshal([]byte(inputArgs["appVersion"]), &appVersion)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg appVersion", err))
				}
			}
			var version string
			if inputArgs["version"] != nil {
				err = json.Unmarshal([]byte(inputArgs["version"]), &version)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg version", err))
				}
			}
			var dependencyUpdate bool
			if inputArgs["dependencyUpdate"] != nil {
				err = json.Unmarshal([]byte(inputArgs["dependencyUpdate"]), &dependencyUpdate)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg dependencyUpdate", err))
				}
			}
			return (*Helm).Package(&parent, ctx, chart, appVersion, version, dependencyUpdate)
		case "Push":
			var parent Helm
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var pkg *dagger.File
			if inputArgs["pkg"] != nil {
				err = json.Unmarshal([]byte(inputArgs["pkg"]), &pkg)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg pkg", err))
				}
			}
			var registry string
			if inputArgs["registry"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registry"]), &registry)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registry", err))
				}
			}
			var plainHttp bool
			if inputArgs["plainHttp"] != nil {
				err = json.Unmarshal([]byte(inputArgs["plainHttp"]), &plainHttp)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg plainHttp", err))
				}
			}
			var insecureSkipTlsVerify bool
			if inputArgs["insecureSkipTlsVerify"] != nil {
				err = json.Unmarshal([]byte(inputArgs["insecureSkipTlsVerify"]), &insecureSkipTlsVerify)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg insecureSkipTlsVerify", err))
				}
			}
			var caFile *dagger.File
			if inputArgs["caFile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["caFile"]), &caFile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg caFile", err))
				}
			}
			var certFile *dagger.File
			if inputArgs["certFile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["certFile"]), &certFile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg certFile", err))
				}
			}
			var keyFile *dagger.Secret
			if inputArgs["keyFile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["keyFile"]), &keyFile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg keyFile", err))
				}
			}
			return nil, (*Helm).Push(&parent, ctx, pkg, registry, plainHttp, insecureSkipTlsVerify, caFile, certFile, keyFile)
		case "WithKubeconfigFile":
			var parent Helm
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var file *dagger.File
			if inputArgs["file"] != nil {
				err = json.Unmarshal([]byte(inputArgs["file"]), &file)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg file", err))
				}
			}
			return (*Helm).WithKubeconfigFile(&parent, file), nil
		case "WithKubeconfigSecret":
			var parent Helm
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var secret *dagger.Secret
			if inputArgs["secret"] != nil {
				err = json.Unmarshal([]byte(inputArgs["secret"]), &secret)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg secret", err))
				}
			}
			return (*Helm).WithKubeconfigSecret(&parent, secret), nil
		case "WithRegistryAuth":
			var parent Helm
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var address string
			if inputArgs["address"] != nil {
				err = json.Unmarshal([]byte(inputArgs["address"]), &address)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg address", err))
				}
			}
			var username string
			if inputArgs["username"] != nil {
				err = json.Unmarshal([]byte(inputArgs["username"]), &username)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg username", err))
				}
			}
			var secret *dagger.Secret
			if inputArgs["secret"] != nil {
				err = json.Unmarshal([]byte(inputArgs["secret"]), &secret)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg secret", err))
				}
			}
			return (*Helm).WithRegistryAuth(&parent, address, username, secret), nil
		case "WithoutRegistryAuth":
			var parent Helm
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var address string
			if inputArgs["address"] != nil {
				err = json.Unmarshal([]byte(inputArgs["address"]), &address)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg address", err))
				}
			}
			return (*Helm).WithoutRegistryAuth(&parent, address), nil
		case "":
			var parent Helm
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var version string
			if inputArgs["version"] != nil {
				err = json.Unmarshal([]byte(inputArgs["version"]), &version)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg version", err))
				}
			}
			var container *dagger.Container
			if inputArgs["container"] != nil {
				err = json.Unmarshal([]byte(inputArgs["container"]), &container)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg container", err))
				}
			}
			return New(version, container), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "Package":
		switch fnName {
		case "Install":
			var parent Package
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var name string
			if inputArgs["name"] != nil {
				err = json.Unmarshal([]byte(inputArgs["name"]), &name)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg name", err))
				}
			}
			var atomic bool
			if inputArgs["atomic"] != nil {
				err = json.Unmarshal([]byte(inputArgs["atomic"]), &atomic)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg atomic", err))
				}
			}
			var caFile *dagger.File
			if inputArgs["caFile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["caFile"]), &caFile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg caFile", err))
				}
			}
			var certFile *dagger.File
			if inputArgs["certFile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["certFile"]), &certFile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg certFile", err))
				}
			}
			var createNamespace bool
			if inputArgs["createNamespace"] != nil {
				err = json.Unmarshal([]byte(inputArgs["createNamespace"]), &createNamespace)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg createNamespace", err))
				}
			}
			var dependencyUpdate bool
			if inputArgs["dependencyUpdate"] != nil {
				err = json.Unmarshal([]byte(inputArgs["dependencyUpdate"]), &dependencyUpdate)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg dependencyUpdate", err))
				}
			}
			var description string
			if inputArgs["description"] != nil {
				err = json.Unmarshal([]byte(inputArgs["description"]), &description)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg description", err))
				}
			}
			var disableOpenapiValidation bool
			if inputArgs["disableOpenapiValidation"] != nil {
				err = json.Unmarshal([]byte(inputArgs["disableOpenapiValidation"]), &disableOpenapiValidation)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg disableOpenapiValidation", err))
				}
			}
			var enableDns bool
			if inputArgs["enableDns"] != nil {
				err = json.Unmarshal([]byte(inputArgs["enableDns"]), &enableDns)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg enableDns", err))
				}
			}
			var force bool
			if inputArgs["force"] != nil {
				err = json.Unmarshal([]byte(inputArgs["force"]), &force)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg force", err))
				}
			}
			var generateName bool
			if inputArgs["generateName"] != nil {
				err = json.Unmarshal([]byte(inputArgs["generateName"]), &generateName)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg generateName", err))
				}
			}
			var insecureSkipTlsVerify bool
			if inputArgs["insecureSkipTlsVerify"] != nil {
				err = json.Unmarshal([]byte(inputArgs["insecureSkipTlsVerify"]), &insecureSkipTlsVerify)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg insecureSkipTlsVerify", err))
				}
			}
			var keyFile *dagger.Secret
			if inputArgs["keyFile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["keyFile"]), &keyFile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg keyFile", err))
				}
			}
			var labels []string
			if inputArgs["labels"] != nil {
				err = json.Unmarshal([]byte(inputArgs["labels"]), &labels)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg labels", err))
				}
			}
			var nameTemplate string
			if inputArgs["nameTemplate"] != nil {
				err = json.Unmarshal([]byte(inputArgs["nameTemplate"]), &nameTemplate)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg nameTemplate", err))
				}
			}
			var noHooks bool
			if inputArgs["noHooks"] != nil {
				err = json.Unmarshal([]byte(inputArgs["noHooks"]), &noHooks)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg noHooks", err))
				}
			}
			var plainHttp bool
			if inputArgs["plainHttp"] != nil {
				err = json.Unmarshal([]byte(inputArgs["plainHttp"]), &plainHttp)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg plainHttp", err))
				}
			}
			var postRenderer string
			if inputArgs["postRenderer"] != nil {
				err = json.Unmarshal([]byte(inputArgs["postRenderer"]), &postRenderer)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg postRenderer", err))
				}
			}
			var postRendererArgs []string
			if inputArgs["postRendererArgs"] != nil {
				err = json.Unmarshal([]byte(inputArgs["postRendererArgs"]), &postRendererArgs)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg postRendererArgs", err))
				}
			}
			var renderSubchartNotes bool
			if inputArgs["renderSubchartNotes"] != nil {
				err = json.Unmarshal([]byte(inputArgs["renderSubchartNotes"]), &renderSubchartNotes)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg renderSubchartNotes", err))
				}
			}
			var replace bool
			if inputArgs["replace"] != nil {
				err = json.Unmarshal([]byte(inputArgs["replace"]), &replace)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg replace", err))
				}
			}
			var skipCrds bool
			if inputArgs["skipCrds"] != nil {
				err = json.Unmarshal([]byte(inputArgs["skipCrds"]), &skipCrds)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg skipCrds", err))
				}
			}
			var timeout string
			if inputArgs["timeout"] != nil {
				err = json.Unmarshal([]byte(inputArgs["timeout"]), &timeout)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg timeout", err))
				}
			}
			var values []*dagger.File
			if inputArgs["values"] != nil {
				err = json.Unmarshal([]byte(inputArgs["values"]), &values)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg values", err))
				}
			}
			var verify bool
			if inputArgs["verify"] != nil {
				err = json.Unmarshal([]byte(inputArgs["verify"]), &verify)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg verify", err))
				}
			}
			var wait bool
			if inputArgs["wait"] != nil {
				err = json.Unmarshal([]byte(inputArgs["wait"]), &wait)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg wait", err))
				}
			}
			var waitForJobs bool
			if inputArgs["waitForJobs"] != nil {
				err = json.Unmarshal([]byte(inputArgs["waitForJobs"]), &waitForJobs)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg waitForJobs", err))
				}
			}
			var namespace string
			if inputArgs["namespace"] != nil {
				err = json.Unmarshal([]byte(inputArgs["namespace"]), &namespace)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg namespace", err))
				}
			}
			return (*Package).Install(&parent, ctx, name, atomic, caFile, certFile, createNamespace, dependencyUpdate, description, disableOpenapiValidation, enableDns, force, generateName, insecureSkipTlsVerify, keyFile, labels, nameTemplate, noHooks, plainHttp, postRenderer, postRendererArgs, renderSubchartNotes, replace, skipCrds, timeout, values, verify, wait, waitForJobs, namespace)
		case "Publish":
			var parent Package
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var registry string
			if inputArgs["registry"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registry"]), &registry)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registry", err))
				}
			}
			var plainHttp bool
			if inputArgs["plainHttp"] != nil {
				err = json.Unmarshal([]byte(inputArgs["plainHttp"]), &plainHttp)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg plainHttp", err))
				}
			}
			var insecureSkipTlsVerify bool
			if inputArgs["insecureSkipTlsVerify"] != nil {
				err = json.Unmarshal([]byte(inputArgs["insecureSkipTlsVerify"]), &insecureSkipTlsVerify)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg insecureSkipTlsVerify", err))
				}
			}
			var caFile *dagger.File
			if inputArgs["caFile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["caFile"]), &caFile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg caFile", err))
				}
			}
			var certFile *dagger.File
			if inputArgs["certFile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["certFile"]), &certFile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg certFile", err))
				}
			}
			var keyFile *dagger.Secret
			if inputArgs["keyFile"] != nil {
				err = json.Unmarshal([]byte(inputArgs["keyFile"]), &keyFile)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg keyFile", err))
				}
			}
			return nil, (*Package).Publish(&parent, ctx, registry, plainHttp, insecureSkipTlsVerify, caFile, certFile, keyFile)
		case "WithKubeconfigFile":
			var parent Package
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var file *dagger.File
			if inputArgs["file"] != nil {
				err = json.Unmarshal([]byte(inputArgs["file"]), &file)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg file", err))
				}
			}
			return (*Package).WithKubeconfigFile(&parent, file), nil
		case "WithKubeconfigSecret":
			var parent Package
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var secret *dagger.Secret
			if inputArgs["secret"] != nil {
				err = json.Unmarshal([]byte(inputArgs["secret"]), &secret)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg secret", err))
				}
			}
			return (*Package).WithKubeconfigSecret(&parent, secret), nil
		case "WithRegistryAuth":
			var parent Package
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var address string
			if inputArgs["address"] != nil {
				err = json.Unmarshal([]byte(inputArgs["address"]), &address)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg address", err))
				}
			}
			var username string
			if inputArgs["username"] != nil {
				err = json.Unmarshal([]byte(inputArgs["username"]), &username)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg username", err))
				}
			}
			var secret *dagger.Secret
			if inputArgs["secret"] != nil {
				err = json.Unmarshal([]byte(inputArgs["secret"]), &secret)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg secret", err))
				}
			}
			return (*Package).WithRegistryAuth(&parent, address, username, secret), nil
		case "WithoutRegistryAuth":
			var parent Package
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var address string
			if inputArgs["address"] != nil {
				err = json.Unmarshal([]byte(inputArgs["address"]), &address)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg address", err))
				}
			}
			return (*Package).WithoutRegistryAuth(&parent, address), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "Release":
		switch fnName {
		case "Test":
			var parent Release
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var filter []string
			if inputArgs["filter"] != nil {
				err = json.Unmarshal([]byte(inputArgs["filter"]), &filter)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg filter", err))
				}
			}
			var logs bool
			if inputArgs["logs"] != nil {
				err = json.Unmarshal([]byte(inputArgs["logs"]), &logs)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg logs", err))
				}
			}
			var timeout string
			if inputArgs["timeout"] != nil {
				err = json.Unmarshal([]byte(inputArgs["timeout"]), &timeout)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg timeout", err))
				}
			}
			return (*Release).Test(&parent, ctx, filter, logs, timeout)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "":
		return dag.Module().
			WithDescription("The package manager for Kubernetes.\n").
			WithObject(
				dag.TypeDef().WithObject("Helm", dagger.TypeDefWithObjectOpts{SourceMap: dag.SourceMap("main.go", 17, 6)}).
					WithFunction(
						dag.Function("Chart",
							dag.TypeDef().WithObject("Chart")).
							WithDescription("Returns a Helm chart from a source directory.").
							WithSourceMap(dag.SourceMap("chart.go", 9, 1)).
							WithArg("source", dag.TypeDef().WithObject("Directory"), dagger.FunctionWithArgOpts{Description: "A directory containing a Helm chart.", SourceMap: dag.SourceMap("chart.go", 11, 2)})).
					WithFunction(
						dag.Function("Create",
							dag.TypeDef().WithObject("Chart")).
							WithDescription("Create a new chart directory along with the common files and directories used in a chart.").
							WithSourceMap(dag.SourceMap("main.go", 108, 1)).
							WithArg("name", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 108, 23)})).
					WithFunction(
						dag.Function("Lint",
							dag.TypeDef().WithObject("Container")).
							WithDescription("Lint a Helm chart directory.").
							WithSourceMap(dag.SourceMap("main.go", 122, 1)).
							WithArg("chart", dag.TypeDef().WithObject("Directory"), dagger.FunctionWithArgOpts{Description: "A directory containing a Helm chart.", SourceMap: dag.SourceMap("main.go", 126, 2)})).
					WithFunction(
						dag.Function("Login",
							dag.TypeDef().WithObject("Helm")).
							WithDescription("Authenticate to an OCI registry.\n\nNote: Login stores credentials in the filesystem in plain text. Use WithRegistryAuth as a safer alternative.").
							WithSourceMap(dag.SourceMap("main.go", 214, 1)).
							WithArg("host", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Host of the OCI registry.", SourceMap: dag.SourceMap("main.go", 218, 2)}).
							WithArg("username", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Registry username.", SourceMap: dag.SourceMap("main.go", 221, 2)}).
							WithArg("password", dag.TypeDef().WithObject("Secret"), dagger.FunctionWithArgOpts{Description: "Registry password.", SourceMap: dag.SourceMap("main.go", 224, 2)}).
							WithArg("insecure", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Allow connections to TLS registry without certs.", SourceMap: dag.SourceMap("main.go", 229, 2)})).
					WithFunction(
						dag.Function("Logout",
							dag.TypeDef().WithObject("Helm")).
							WithDescription("Remove credentials stored for an OCI registry.").
							WithSourceMap(dag.SourceMap("main.go", 253, 1)).
							WithArg("host", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 253, 23)})).
					WithFunction(
						dag.Function("Package",
							dag.TypeDef().WithObject("File")).
							WithDescription("Build a Helm chart package.").
							WithSourceMap(dag.SourceMap("main.go", 150, 1)).
							WithArg("chart", dag.TypeDef().WithObject("Directory"), dagger.FunctionWithArgOpts{Description: "A directory containing a Helm chart.", SourceMap: dag.SourceMap("main.go", 154, 2)}).
							WithArg("appVersion", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Set the appVersion on the chart to this version.", SourceMap: dag.SourceMap("main.go", 159, 2)}).
							WithArg("version", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Set the version on the chart to this semver version.", SourceMap: dag.SourceMap("main.go", 164, 2)}).
							WithArg("dependencyUpdate", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Update dependencies from \"Chart.yaml\" to dir \"charts/\" before packaging.", SourceMap: dag.SourceMap("main.go", 169, 2)})).
					WithFunction(
						dag.Function("Push",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("Push a Helm chart package to an OCI registry.").
							WithCachePolicy(dagger.FunctionCachePolicyNever).
							WithSourceMap(dag.SourceMap("main.go", 267, 1)).
							WithArg("pkg", dag.TypeDef().WithObject("File"), dagger.FunctionWithArgOpts{Description: "Packaged Helm chart.", SourceMap: dag.SourceMap("main.go", 271, 2)}).
							WithArg("registry", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "OCI registry to push to (including the path except the chart name).", SourceMap: dag.SourceMap("main.go", 274, 2)}).
							WithArg("plainHttp", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Use insecure HTTP connections for the chart upload.", SourceMap: dag.SourceMap("main.go", 279, 2)}).
							WithArg("insecureSkipTlsVerify", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Skip tls certificate checks for the chart upload.", SourceMap: dag.SourceMap("main.go", 284, 2)}).
							WithArg("caFile", dag.TypeDef().WithObject("File").WithOptional(true), dagger.FunctionWithArgOpts{Description: "Verify certificates of HTTPS-enabled servers using this CA bundle.", SourceMap: dag.SourceMap("main.go", 289, 2)}).
							WithArg("certFile", dag.TypeDef().WithObject("File").WithOptional(true), dagger.FunctionWithArgOpts{Description: "Identify registry client using this SSL certificate file.", SourceMap: dag.SourceMap("main.go", 294, 2)}).
							WithArg("keyFile", dag.TypeDef().WithObject("Secret").WithOptional(true), dagger.FunctionWithArgOpts{Description: "Identify registry client using this SSL key file.", SourceMap: dag.SourceMap("main.go", 299, 2)})).
					WithFunction(
						dag.Function("WithKubeconfigFile",
							dag.TypeDef().WithObject("Helm")).
							WithDescription("Mount a file as the kubeconfig file.").
							WithSourceMap(dag.SourceMap("main.go", 90, 1)).
							WithArg("file", dag.TypeDef().WithObject("File"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 90, 35)})).
					WithFunction(
						dag.Function("WithKubeconfigSecret",
							dag.TypeDef().WithObject("Helm")).
							WithDescription("Mount a secret as the kubeconfig file.").
							WithSourceMap(dag.SourceMap("main.go", 99, 1)).
							WithArg("secret", dag.TypeDef().WithObject("Secret"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 99, 37)})).
					WithFunction(
						dag.Function("WithRegistryAuth",
							dag.TypeDef().WithObject("Helm")).
							WithDescription("Add credentials for a registry.\n\nNote: WithRegistryAuth overrides any previous or subsequent calls to Login/Logout.").
							WithSourceMap(dag.SourceMap("main.go", 76, 1)).
							WithArg("address", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 76, 33)}).
							WithArg("username", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 76, 49)}).
							WithArg("secret", dag.TypeDef().WithObject("Secret"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 76, 66)})).
					WithFunction(
						dag.Function("WithoutRegistryAuth",
							dag.TypeDef().WithObject("Helm")).
							WithDescription("Removes credentials for a registry.").
							WithSourceMap(dag.SourceMap("main.go", 83, 1)).
							WithArg("address", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 83, 36)})).
					WithField("Container", dag.TypeDef().WithObject("Container"), dagger.TypeDefWithFieldOpts{SourceMap: dag.SourceMap("main.go", 18, 2)}).
					WithConstructor(
						dag.Function("New",
							dag.TypeDef().WithObject("Helm")).
							WithSourceMap(dag.SourceMap("main.go", 24, 1)).
							WithArg("version", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Version (image tag) to use from the official image repository as a base container.", SourceMap: dag.SourceMap("main.go", 27, 2)}).
							WithArg("container", dag.TypeDef().WithObject("Container").WithOptional(true), dagger.FunctionWithArgOpts{Description: "Custom container to use as a base container.", SourceMap: dag.SourceMap("main.go", 31, 2)}))).
			WithObject(
				dag.TypeDef().WithObject("Chart", dagger.TypeDefWithObjectOpts{Description: "A Helm chart.", SourceMap: dag.SourceMap("chart.go", 20, 6)}).
					WithFunction(
						dag.Function("Install",
							dag.TypeDef().WithObject("Release")).
							WithDescription("Install a Helm chart.").
							WithSourceMap(dag.SourceMap("release.go", 13, 1)).
							WithArg("name", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Helm release name.", SourceMap: dag.SourceMap("release.go", 17, 2)}).
							WithArg("atomic", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "If set, the installation process deletes the installation on failure. Wait flag will be set automatically if atomic is used.", SourceMap: dag.SourceMap("release.go", 22, 2)}).
							WithArg("caFile", dag.TypeDef().WithObject("File").WithOptional(true), dagger.FunctionWithArgOpts{Description: "Verify certificates of HTTPS-enabled servers using this CA bundle.", SourceMap: dag.SourceMap("release.go", 27, 2)}).
							WithArg("certFile", dag.TypeDef().WithObject("File").WithOptional(true), dagger.FunctionWithArgOpts{Description: "Identify HTTPS client using this SSL certificate file.", SourceMap: dag.SourceMap("release.go", 32, 2)}).
							WithArg("createNamespace", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Create the release namespace if not present.", SourceMap: dag.SourceMap("release.go", 37, 2)}).
							WithArg("dependencyUpdate", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Update dependencies if they are missing before installing the chart.", SourceMap: dag.SourceMap("release.go", 42, 2)}).
							WithArg("description", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Add a custom description.", SourceMap: dag.SourceMap("release.go", 47, 2)}).
							WithArg("disableOpenapiValidation", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "If set, the installation process will not validate rendered templates against the Kubernetes OpenAPI Schema.", SourceMap: dag.SourceMap("release.go", 52, 2)}).
							WithArg("enableDns", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Enable DNS lookups when rendering templates.", SourceMap: dag.SourceMap("release.go", 62, 2)}).
							WithArg("force", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Force resource updates through a replacement strategy.", SourceMap: dag.SourceMap("release.go", 67, 2)}).
							WithArg("generateName", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Generate the name.", SourceMap: dag.SourceMap("release.go", 72, 2)}).
							WithArg("insecureSkipTlsVerify", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Skip tls certificate checks for the chart download.", SourceMap: dag.SourceMap("release.go", 82, 2)}).
							WithArg("keyFile", dag.TypeDef().WithObject("Secret").WithOptional(true), dagger.FunctionWithArgOpts{Description: "Identify HTTPS client using this SSL key file.", SourceMap: dag.SourceMap("release.go", 87, 2)}).
							WithArg("labels", dag.TypeDef().WithListOf(dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Labels that would be added to release metadata.", SourceMap: dag.SourceMap("release.go", 92, 2)}).
							WithArg("nameTemplate", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Specify template used to name the release.", SourceMap: dag.SourceMap("release.go", 97, 2)}).
							WithArg("noHooks", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Prevent hooks from running during install.", SourceMap: dag.SourceMap("release.go", 102, 2)}).
							WithArg("plainHttp", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Use insecure HTTP connections for the chart download.", SourceMap: dag.SourceMap("release.go", 111, 2)}).
							WithArg("postRenderer", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "The path to an executable to be used for post rendering. If it exists in $PATH, the binary will be used, otherwise it will try to look for the executable at the given path.", SourceMap: dag.SourceMap("release.go", 116, 2)}).
							WithArg("postRendererArgs", dag.TypeDef().WithListOf(dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Arguments to the post-renderer.", SourceMap: dag.SourceMap("release.go", 121, 2)}).
							WithArg("renderSubchartNotes", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "If set, render subchart notes along with the parent.", SourceMap: dag.SourceMap("release.go", 126, 2)}).
							WithArg("replace", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Re-use the given name, only if that name is a deleted release which remains in the history. This is unsafe in production.", SourceMap: dag.SourceMap("release.go", 131, 2)}).
							WithArg("skipCrds", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "If set, no CRDs will be installed. By default, CRDs are installed if not already present.", SourceMap: dag.SourceMap("release.go", 144, 2)}).
							WithArg("timeout", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Time to wait for any individual Kubernetes operation (like Jobs for hooks).", SourceMap: dag.SourceMap("release.go", 149, 2)}).
							WithArg("values", dag.TypeDef().WithListOf(dag.TypeDef().WithObject("File")).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Specify values in a YAML file.", SourceMap: dag.SourceMap("release.go", 156, 2)}).
							WithArg("verify", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Verify the package before using it.", SourceMap: dag.SourceMap("release.go", 161, 2)}).
							WithArg("wait", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "If set, will wait until all Pods, PVCs, Services, and minimum number of Pods of a Deployment, StatefulSet, or ReplicaSet are in a ready state before marking the release as successful. It will wait for as long as timeout.", SourceMap: dag.SourceMap("release.go", 166, 2)}).
							WithArg("waitForJobs", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "If set and wait enabled, will wait until all Jobs have been completed before marking the release as successful. It will wait for as long as timeout.", SourceMap: dag.SourceMap("release.go", 171, 2)}).
							WithArg("namespace", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Namespace scope for this request.", SourceMap: dag.SourceMap("release.go", 178, 2)})).
					WithFunction(
						dag.Function("Lint",
							dag.TypeDef().WithObject("Container")).
							WithDescription("Lint a Helm chart.").
							WithSourceMap(dag.SourceMap("chart.go", 28, 1))).
					WithFunction(
						dag.Function("Package",
							dag.TypeDef().WithObject("Package")).
							WithDescription("Build a Helm chart package.").
							WithSourceMap(dag.SourceMap("chart.go", 44, 1)).
							WithArg("appVersion", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Set the appVersion on the chart to this version.", SourceMap: dag.SourceMap("chart.go", 50, 2)}).
							WithArg("version", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Set the version on the chart to this semver version.", SourceMap: dag.SourceMap("chart.go", 55, 2)}).
							WithArg("dependencyUpdate", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Update dependencies from \"Chart.yaml\" to dir \"charts/\" before packaging.", SourceMap: dag.SourceMap("chart.go", 60, 2)})).
					WithField("Directory", dag.TypeDef().WithObject("Directory"), dagger.TypeDefWithFieldOpts{SourceMap: dag.SourceMap("chart.go", 21, 2)})).
			WithObject(
				dag.TypeDef().WithObject("Release", dagger.TypeDefWithObjectOpts{SourceMap: dag.SourceMap("release.go", 637, 6)}).
					WithFunction(
						dag.Function("Test",
							dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).
							WithDescription("Run Helm tests.").
							WithSourceMap(dag.SourceMap("release.go", 646, 1)).
							WithArg("filter", dag.TypeDef().WithListOf(dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Specify tests by attribute (currently \"name\") using attribute=value syntax or '!attribute=value' to exclude a test.", SourceMap: dag.SourceMap("release.go", 652, 2)}).
							WithArg("logs", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Dump the logs from test pods (this runs after all tests are complete, but before any cleanup).", SourceMap: dag.SourceMap("release.go", 657, 2)}).
							WithArg("timeout", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Time to wait for any individual Kubernetes operation (like Jobs for hooks) (default 5m0s).", SourceMap: dag.SourceMap("release.go", 662, 2)})).
					WithField("Name", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.TypeDefWithFieldOpts{SourceMap: dag.SourceMap("release.go", 638, 2)}).
					WithField("Namespace", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.TypeDefWithFieldOpts{SourceMap: dag.SourceMap("release.go", 639, 2)})).
			WithObject(
				dag.TypeDef().WithObject("Package", dagger.TypeDefWithObjectOpts{Description: "A Helm chart package.", SourceMap: dag.SourceMap("chart.go", 33, 6)}).
					WithFunction(
						dag.Function("Install",
							dag.TypeDef().WithObject("Release")).
							WithDescription("Install a Helm chart.").
							WithSourceMap(dag.SourceMap("release.go", 232, 1)).
							WithArg("name", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "Helm release name.", SourceMap: dag.SourceMap("release.go", 236, 2)}).
							WithArg("atomic", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "If set, the installation process deletes the installation on failure. Wait flag will be set automatically if atomic is used.", SourceMap: dag.SourceMap("release.go", 241, 2)}).
							WithArg("caFile", dag.TypeDef().WithObject("File").WithOptional(true), dagger.FunctionWithArgOpts{Description: "Verify certificates of HTTPS-enabled servers using this CA bundle.", SourceMap: dag.SourceMap("release.go", 246, 2)}).
							WithArg("certFile", dag.TypeDef().WithObject("File").WithOptional(true), dagger.FunctionWithArgOpts{Description: "Identify HTTPS client using this SSL certificate file.", SourceMap: dag.SourceMap("release.go", 251, 2)}).
							WithArg("createNamespace", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Create the release namespace if not present.", SourceMap: dag.SourceMap("release.go", 256, 2)}).
							WithArg("dependencyUpdate", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Update dependencies if they are missing before installing the chart.", SourceMap: dag.SourceMap("release.go", 261, 2)}).
							WithArg("description", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Add a custom description.", SourceMap: dag.SourceMap("release.go", 266, 2)}).
							WithArg("disableOpenapiValidation", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "If set, the installation process will not validate rendered templates against the Kubernetes OpenAPI Schema.", SourceMap: dag.SourceMap("release.go", 271, 2)}).
							WithArg("enableDns", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Enable DNS lookups when rendering templates.", SourceMap: dag.SourceMap("release.go", 281, 2)}).
							WithArg("force", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Force resource updates through a replacement strategy.", SourceMap: dag.SourceMap("release.go", 286, 2)}).
							WithArg("generateName", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Generate the name.", SourceMap: dag.SourceMap("release.go", 291, 2)}).
							WithArg("insecureSkipTlsVerify", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Skip tls certificate checks for the chart download.", SourceMap: dag.SourceMap("release.go", 301, 2)}).
							WithArg("keyFile", dag.TypeDef().WithObject("Secret").WithOptional(true), dagger.FunctionWithArgOpts{Description: "Identify HTTPS client using this SSL key file.", SourceMap: dag.SourceMap("release.go", 306, 2)}).
							WithArg("labels", dag.TypeDef().WithListOf(dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Labels that would be added to release metadata.", SourceMap: dag.SourceMap("release.go", 311, 2)}).
							WithArg("nameTemplate", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Specify template used to name the release.", SourceMap: dag.SourceMap("release.go", 316, 2)}).
							WithArg("noHooks", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Prevent hooks from running during install.", SourceMap: dag.SourceMap("release.go", 321, 2)}).
							WithArg("plainHttp", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Use insecure HTTP connections for the chart download.", SourceMap: dag.SourceMap("release.go", 330, 2)}).
							WithArg("postRenderer", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "The path to an executable to be used for post rendering. If it exists in $PATH, the binary will be used, otherwise it will try to look for the executable at the given path.", SourceMap: dag.SourceMap("release.go", 335, 2)}).
							WithArg("postRendererArgs", dag.TypeDef().WithListOf(dag.TypeDef().WithKind(dagger.TypeDefKindStringKind)).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Arguments to the post-renderer.", SourceMap: dag.SourceMap("release.go", 340, 2)}).
							WithArg("renderSubchartNotes", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "If set, render subchart notes along with the parent.", SourceMap: dag.SourceMap("release.go", 345, 2)}).
							WithArg("replace", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Re-use the given name, only if that name is a deleted release which remains in the history. This is unsafe in production.", SourceMap: dag.SourceMap("release.go", 350, 2)}).
							WithArg("skipCrds", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "If set, no CRDs will be installed. By default, CRDs are installed if not already present.", SourceMap: dag.SourceMap("release.go", 363, 2)}).
							WithArg("timeout", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Time to wait for any individual Kubernetes operation (like Jobs for hooks).", SourceMap: dag.SourceMap("release.go", 368, 2)}).
							WithArg("values", dag.TypeDef().WithListOf(dag.TypeDef().WithObject("File")).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Specify values in a YAML file.", SourceMap: dag.SourceMap("release.go", 375, 2)}).
							WithArg("verify", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Verify the package before using it.", SourceMap: dag.SourceMap("release.go", 380, 2)}).
							WithArg("wait", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "If set, will wait until all Pods, PVCs, Services, and minimum number of Pods of a Deployment, StatefulSet, or ReplicaSet are in a ready state before marking the release as successful. It will wait for as long as timeout.", SourceMap: dag.SourceMap("release.go", 385, 2)}).
							WithArg("waitForJobs", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "If set and wait enabled, will wait until all Jobs have been completed before marking the release as successful. It will wait for as long as timeout.", SourceMap: dag.SourceMap("release.go", 390, 2)}).
							WithArg("namespace", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Namespace scope for this request.", SourceMap: dag.SourceMap("release.go", 397, 2)})).
					WithFunction(
						dag.Function("Publish",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("Publishes this Helm chart package to an OCI registry.").
							WithSourceMap(dag.SourceMap("chart.go", 103, 1)).
							WithArg("registry", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{Description: "OCI registry to push to (including the path except the chart name).", SourceMap: dag.SourceMap("chart.go", 107, 2)}).
							WithArg("plainHttp", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Use insecure HTTP connections for the chart upload.", SourceMap: dag.SourceMap("chart.go", 112, 2)}).
							WithArg("insecureSkipTlsVerify", dag.TypeDef().WithKind(dagger.TypeDefKindBooleanKind).WithOptional(true), dagger.FunctionWithArgOpts{Description: "Skip tls certificate checks for the chart upload.", SourceMap: dag.SourceMap("chart.go", 117, 2)}).
							WithArg("caFile", dag.TypeDef().WithObject("File").WithOptional(true), dagger.FunctionWithArgOpts{Description: "Verify certificates of HTTPS-enabled servers using this CA bundle.", SourceMap: dag.SourceMap("chart.go", 122, 2)}).
							WithArg("certFile", dag.TypeDef().WithObject("File").WithOptional(true), dagger.FunctionWithArgOpts{Description: "Identify registry client using this SSL certificate file.", SourceMap: dag.SourceMap("chart.go", 127, 2)}).
							WithArg("keyFile", dag.TypeDef().WithObject("Secret").WithOptional(true), dagger.FunctionWithArgOpts{Description: "Identify registry client using this SSL key file.", SourceMap: dag.SourceMap("chart.go", 132, 2)})).
					WithFunction(
						dag.Function("WithKubeconfigFile",
							dag.TypeDef().WithObject("Package")).
							WithDescription("Mount a file as the kubeconfig file.").
							WithSourceMap(dag.SourceMap("chart.go", 89, 1)).
							WithArg("file", dag.TypeDef().WithObject("File"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("chart.go", 89, 38)})).
					WithFunction(
						dag.Function("WithKubeconfigSecret",
							dag.TypeDef().WithObject("Package")).
							WithDescription("Mount a secret as the kubeconfig file.").
							WithSourceMap(dag.SourceMap("chart.go", 96, 1)).
							WithArg("secret", dag.TypeDef().WithObject("Secret"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("chart.go", 96, 40)})).
					WithFunction(
						dag.Function("WithRegistryAuth",
							dag.TypeDef().WithObject("Package")).
							WithDescription("Add credentials for a registry.").
							WithSourceMap(dag.SourceMap("chart.go", 75, 1)).
							WithArg("address", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("chart.go", 75, 36)}).
							WithArg("username", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("chart.go", 75, 52)}).
							WithArg("secret", dag.TypeDef().WithObject("Secret"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("chart.go", 75, 69)})).
					WithFunction(
						dag.Function("WithoutRegistryAuth",
							dag.TypeDef().WithObject("Package")).
							WithDescription("Removes credentials for a registry.").
							WithSourceMap(dag.SourceMap("chart.go", 82, 1)).
							WithArg("address", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("chart.go", 82, 39)})).
					WithField("File", dag.TypeDef().WithObject("File"), dagger.TypeDefWithFieldOpts{SourceMap: dag.SourceMap("chart.go", 34, 2)})), nil
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
