// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: shopping_list_service.proto

package genpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanRequest) Reset() {
	*x = GetPlanRequest{}
	mi := &file_shopping_list_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanRequest) ProtoMessage() {}

func (x *GetPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanRequest.ProtoReflect.Descriptor instead.
func (*GetPlanRequest) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{0}
}

type GetPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plan          *Plan                  `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	PlanSummary   *PlanSummary           `protobuf:"bytes,2,opt,name=plan_summary,json=planSummary,proto3" json:"plan_summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanResponse) Reset() {
	*x = GetPlanResponse{}
	mi := &file_shopping_list_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanResponse) ProtoMessage() {}

func (x *GetPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanResponse.ProtoReflect.Descriptor instead.
func (*GetPlanResponse) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetPlanResponse) GetPlan() *Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *GetPlanResponse) GetPlanSummary() *PlanSummary {
	if x != nil {
		return x.PlanSummary
	}
	return nil
}

type UpdatePlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plan          *Plan                  `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlanRequest) Reset() {
	*x = UpdatePlanRequest{}
	mi := &file_shopping_list_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlanRequest) ProtoMessage() {}

func (x *UpdatePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlanRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlanRequest) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePlanRequest) GetPlan() *Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

type UpdatePlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlanResponse) Reset() {
	*x = UpdatePlanResponse{}
	mi := &file_shopping_list_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlanResponse) ProtoMessage() {}

func (x *UpdatePlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlanResponse.ProtoReflect.Descriptor instead.
func (*UpdatePlanResponse) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{3}
}

type GetMealsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMealsRequest) Reset() {
	*x = GetMealsRequest{}
	mi := &file_shopping_list_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMealsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMealsRequest) ProtoMessage() {}

func (x *GetMealsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMealsRequest.ProtoReflect.Descriptor instead.
func (*GetMealsRequest) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{4}
}

type GetMealsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meals         []*Meal                `protobuf:"bytes,1,rep,name=meals,proto3" json:"meals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMealsResponse) Reset() {
	*x = GetMealsResponse{}
	mi := &file_shopping_list_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMealsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMealsResponse) ProtoMessage() {}

func (x *GetMealsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMealsResponse.ProtoReflect.Descriptor instead.
func (*GetMealsResponse) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetMealsResponse) GetMeals() []*Meal {
	if x != nil {
		return x.Meals
	}
	return nil
}

type CreateMealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meal          *Meal                  `protobuf:"bytes,1,opt,name=meal,proto3" json:"meal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMealRequest) Reset() {
	*x = CreateMealRequest{}
	mi := &file_shopping_list_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMealRequest) ProtoMessage() {}

func (x *CreateMealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMealRequest.ProtoReflect.Descriptor instead.
func (*CreateMealRequest) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateMealRequest) GetMeal() *Meal {
	if x != nil {
		return x.Meal
	}
	return nil
}

type CreateMealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MealId        int64                  `protobuf:"varint,1,opt,name=meal_id,json=mealId,proto3" json:"meal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMealResponse) Reset() {
	*x = CreateMealResponse{}
	mi := &file_shopping_list_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMealResponse) ProtoMessage() {}

func (x *CreateMealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMealResponse.ProtoReflect.Descriptor instead.
func (*CreateMealResponse) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateMealResponse) GetMealId() int64 {
	if x != nil {
		return x.MealId
	}
	return 0
}

type UpdateMealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meal          *Meal                  `protobuf:"bytes,1,opt,name=meal,proto3" json:"meal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMealRequest) Reset() {
	*x = UpdateMealRequest{}
	mi := &file_shopping_list_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMealRequest) ProtoMessage() {}

func (x *UpdateMealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMealRequest.ProtoReflect.Descriptor instead.
func (*UpdateMealRequest) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateMealRequest) GetMeal() *Meal {
	if x != nil {
		return x.Meal
	}
	return nil
}

type UpdateMealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMealResponse) Reset() {
	*x = UpdateMealResponse{}
	mi := &file_shopping_list_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMealResponse) ProtoMessage() {}

func (x *UpdateMealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMealResponse.ProtoReflect.Descriptor instead.
func (*UpdateMealResponse) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{9}
}

type UpdateMealImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ImageBytes    []byte                 `protobuf:"bytes,2,opt,name=image_bytes,json=imageBytes,proto3" json:"image_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMealImageRequest) Reset() {
	*x = UpdateMealImageRequest{}
	mi := &file_shopping_list_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMealImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMealImageRequest) ProtoMessage() {}

func (x *UpdateMealImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMealImageRequest.ProtoReflect.Descriptor instead.
func (*UpdateMealImageRequest) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateMealImageRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMealImageRequest) GetImageBytes() []byte {
	if x != nil {
		return x.ImageBytes
	}
	return nil
}

type UpdateMealImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMealImageResponse) Reset() {
	*x = UpdateMealImageResponse{}
	mi := &file_shopping_list_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMealImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMealImageResponse) ProtoMessage() {}

func (x *UpdateMealImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMealImageResponse.ProtoReflect.Descriptor instead.
func (*UpdateMealImageResponse) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{11}
}

type DeleteMealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MealId        int64                  `protobuf:"varint,1,opt,name=meal_id,json=mealId,proto3" json:"meal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMealRequest) Reset() {
	*x = DeleteMealRequest{}
	mi := &file_shopping_list_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMealRequest) ProtoMessage() {}

func (x *DeleteMealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMealRequest.ProtoReflect.Descriptor instead.
func (*DeleteMealRequest) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteMealRequest) GetMealId() int64 {
	if x != nil {
		return x.MealId
	}
	return 0
}

type DeleteMealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMealResponse) Reset() {
	*x = DeleteMealResponse{}
	mi := &file_shopping_list_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMealResponse) ProtoMessage() {}

func (x *DeleteMealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMealResponse.ProtoReflect.Descriptor instead.
func (*DeleteMealResponse) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{13}
}

type GetIngredientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIngredientsRequest) Reset() {
	*x = GetIngredientsRequest{}
	mi := &file_shopping_list_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIngredientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIngredientsRequest) ProtoMessage() {}

func (x *GetIngredientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIngredientsRequest.ProtoReflect.Descriptor instead.
func (*GetIngredientsRequest) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{14}
}

type GetIngredientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ingredients   []*Ingredient          `protobuf:"bytes,1,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIngredientsResponse) Reset() {
	*x = GetIngredientsResponse{}
	mi := &file_shopping_list_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIngredientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIngredientsResponse) ProtoMessage() {}

func (x *GetIngredientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIngredientsResponse.ProtoReflect.Descriptor instead.
func (*GetIngredientsResponse) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetIngredientsResponse) GetIngredients() []*Ingredient {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

type CreateIngredientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ingredient    *Ingredient            `protobuf:"bytes,1,opt,name=ingredient,proto3" json:"ingredient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIngredientRequest) Reset() {
	*x = CreateIngredientRequest{}
	mi := &file_shopping_list_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIngredientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIngredientRequest) ProtoMessage() {}

func (x *CreateIngredientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIngredientRequest.ProtoReflect.Descriptor instead.
func (*CreateIngredientRequest) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{16}
}

func (x *CreateIngredientRequest) GetIngredient() *Ingredient {
	if x != nil {
		return x.Ingredient
	}
	return nil
}

type CreateIngredientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IngredientId  int64                  `protobuf:"varint,1,opt,name=ingredient_id,json=ingredientId,proto3" json:"ingredient_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIngredientResponse) Reset() {
	*x = CreateIngredientResponse{}
	mi := &file_shopping_list_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIngredientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIngredientResponse) ProtoMessage() {}

func (x *CreateIngredientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIngredientResponse.ProtoReflect.Descriptor instead.
func (*CreateIngredientResponse) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{17}
}

func (x *CreateIngredientResponse) GetIngredientId() int64 {
	if x != nil {
		return x.IngredientId
	}
	return 0
}

type UpdateIngredientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ingredient    *Ingredient            `protobuf:"bytes,1,opt,name=ingredient,proto3" json:"ingredient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIngredientRequest) Reset() {
	*x = UpdateIngredientRequest{}
	mi := &file_shopping_list_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIngredientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIngredientRequest) ProtoMessage() {}

func (x *UpdateIngredientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIngredientRequest.ProtoReflect.Descriptor instead.
func (*UpdateIngredientRequest) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateIngredientRequest) GetIngredient() *Ingredient {
	if x != nil {
		return x.Ingredient
	}
	return nil
}

type UpdateIngredientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIngredientResponse) Reset() {
	*x = UpdateIngredientResponse{}
	mi := &file_shopping_list_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIngredientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIngredientResponse) ProtoMessage() {}

func (x *UpdateIngredientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIngredientResponse.ProtoReflect.Descriptor instead.
func (*UpdateIngredientResponse) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{19}
}

type DeleteIngredientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IngredientId  int64                  `protobuf:"varint,1,opt,name=ingredient_id,json=ingredientId,proto3" json:"ingredient_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIngredientRequest) Reset() {
	*x = DeleteIngredientRequest{}
	mi := &file_shopping_list_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIngredientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIngredientRequest) ProtoMessage() {}

func (x *DeleteIngredientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIngredientRequest.ProtoReflect.Descriptor instead.
func (*DeleteIngredientRequest) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteIngredientRequest) GetIngredientId() int64 {
	if x != nil {
		return x.IngredientId
	}
	return 0
}

type DeleteIngredientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIngredientResponse) Reset() {
	*x = DeleteIngredientResponse{}
	mi := &file_shopping_list_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIngredientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIngredientResponse) ProtoMessage() {}

func (x *DeleteIngredientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIngredientResponse.ProtoReflect.Descriptor instead.
func (*DeleteIngredientResponse) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{21}
}

type GetIngredientCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIngredientCategoriesRequest) Reset() {
	*x = GetIngredientCategoriesRequest{}
	mi := &file_shopping_list_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIngredientCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIngredientCategoriesRequest) ProtoMessage() {}

func (x *GetIngredientCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIngredientCategoriesRequest.ProtoReflect.Descriptor instead.
func (*GetIngredientCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{22}
}

type GetIngredientCategoriesResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	IngredientCategories []*IngredientCategory  `protobuf:"bytes,1,rep,name=ingredient_categories,json=ingredientCategories,proto3" json:"ingredient_categories,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetIngredientCategoriesResponse) Reset() {
	*x = GetIngredientCategoriesResponse{}
	mi := &file_shopping_list_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIngredientCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIngredientCategoriesResponse) ProtoMessage() {}

func (x *GetIngredientCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIngredientCategoriesResponse.ProtoReflect.Descriptor instead.
func (*GetIngredientCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{23}
}

func (x *GetIngredientCategoriesResponse) GetIngredientCategories() []*IngredientCategory {
	if x != nil {
		return x.IngredientCategories
	}
	return nil
}

type CreateIngredientCategoryRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IngredientCategory *IngredientCategory    `protobuf:"bytes,1,opt,name=ingredient_category,json=ingredientCategory,proto3" json:"ingredient_category,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateIngredientCategoryRequest) Reset() {
	*x = CreateIngredientCategoryRequest{}
	mi := &file_shopping_list_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIngredientCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIngredientCategoryRequest) ProtoMessage() {}

func (x *CreateIngredientCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIngredientCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateIngredientCategoryRequest) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{24}
}

func (x *CreateIngredientCategoryRequest) GetIngredientCategory() *IngredientCategory {
	if x != nil {
		return x.IngredientCategory
	}
	return nil
}

type CreateIngredientCategoryResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	IngredientCategoryId int64                  `protobuf:"varint,1,opt,name=ingredient_category_id,json=ingredientCategoryId,proto3" json:"ingredient_category_id,omitempty"`
	SortIndex            int64                  `protobuf:"varint,2,opt,name=sort_index,json=sortIndex,proto3" json:"sort_index,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateIngredientCategoryResponse) Reset() {
	*x = CreateIngredientCategoryResponse{}
	mi := &file_shopping_list_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIngredientCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIngredientCategoryResponse) ProtoMessage() {}

func (x *CreateIngredientCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIngredientCategoryResponse.ProtoReflect.Descriptor instead.
func (*CreateIngredientCategoryResponse) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{25}
}

func (x *CreateIngredientCategoryResponse) GetIngredientCategoryId() int64 {
	if x != nil {
		return x.IngredientCategoryId
	}
	return 0
}

func (x *CreateIngredientCategoryResponse) GetSortIndex() int64 {
	if x != nil {
		return x.SortIndex
	}
	return 0
}

type UpdateIngredientCategoryRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IngredientCategory *IngredientCategory    `protobuf:"bytes,1,opt,name=ingredient_category,json=ingredientCategory,proto3" json:"ingredient_category,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateIngredientCategoryRequest) Reset() {
	*x = UpdateIngredientCategoryRequest{}
	mi := &file_shopping_list_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIngredientCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIngredientCategoryRequest) ProtoMessage() {}

func (x *UpdateIngredientCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIngredientCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateIngredientCategoryRequest) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateIngredientCategoryRequest) GetIngredientCategory() *IngredientCategory {
	if x != nil {
		return x.IngredientCategory
	}
	return nil
}

type UpdateIngredientCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIngredientCategoryResponse) Reset() {
	*x = UpdateIngredientCategoryResponse{}
	mi := &file_shopping_list_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIngredientCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIngredientCategoryResponse) ProtoMessage() {}

func (x *UpdateIngredientCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIngredientCategoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateIngredientCategoryResponse) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{27}
}

type DeleteIngredientCategoryRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	IngredientCategoryId int64                  `protobuf:"varint,1,opt,name=ingredient_category_id,json=ingredientCategoryId,proto3" json:"ingredient_category_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DeleteIngredientCategoryRequest) Reset() {
	*x = DeleteIngredientCategoryRequest{}
	mi := &file_shopping_list_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIngredientCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIngredientCategoryRequest) ProtoMessage() {}

func (x *DeleteIngredientCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIngredientCategoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteIngredientCategoryRequest) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteIngredientCategoryRequest) GetIngredientCategoryId() int64 {
	if x != nil {
		return x.IngredientCategoryId
	}
	return 0
}

type DeleteIngredientCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIngredientCategoryResponse) Reset() {
	*x = DeleteIngredientCategoryResponse{}
	mi := &file_shopping_list_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIngredientCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIngredientCategoryResponse) ProtoMessage() {}

func (x *DeleteIngredientCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIngredientCategoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteIngredientCategoryResponse) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{29}
}

type SwapIngredientCategoriesRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	IngredientCategoryA int64                  `protobuf:"varint,1,opt,name=ingredient_category_a,json=ingredientCategoryA,proto3" json:"ingredient_category_a,omitempty"`
	IngredientCategoryB int64                  `protobuf:"varint,2,opt,name=ingredient_category_b,json=ingredientCategoryB,proto3" json:"ingredient_category_b,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SwapIngredientCategoriesRequest) Reset() {
	*x = SwapIngredientCategoriesRequest{}
	mi := &file_shopping_list_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwapIngredientCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapIngredientCategoriesRequest) ProtoMessage() {}

func (x *SwapIngredientCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapIngredientCategoriesRequest.ProtoReflect.Descriptor instead.
func (*SwapIngredientCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{30}
}

func (x *SwapIngredientCategoriesRequest) GetIngredientCategoryA() int64 {
	if x != nil {
		return x.IngredientCategoryA
	}
	return 0
}

func (x *SwapIngredientCategoriesRequest) GetIngredientCategoryB() int64 {
	if x != nil {
		return x.IngredientCategoryB
	}
	return 0
}

type SwapIngredientCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwapIngredientCategoriesResponse) Reset() {
	*x = SwapIngredientCategoriesResponse{}
	mi := &file_shopping_list_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwapIngredientCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapIngredientCategoriesResponse) ProtoMessage() {}

func (x *SwapIngredientCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_list_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapIngredientCategoriesResponse.ProtoReflect.Descriptor instead.
func (*SwapIngredientCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_shopping_list_service_proto_rawDescGZIP(), []int{31}
}

var File_shopping_list_service_proto protoreflect.FileDescriptor

const file_shopping_list_service_proto_rawDesc = "" +
	"\n" +
	"\x1bshopping_list_service.proto\x1a\n" +
	"plan.proto\x1a\n" +
	"meal.proto\x1a\x10ingredient.proto\x1a\x19ingredient_category.proto\"\x10\n" +
	"\x0eGetPlanRequest\"]\n" +
	"\x0fGetPlanResponse\x12\x19\n" +
	"\x04plan\x18\x01 \x01(\v2\x05.PlanR\x04plan\x12/\n" +
	"\fplan_summary\x18\x02 \x01(\v2\f.PlanSummaryR\vplanSummary\".\n" +
	"\x11UpdatePlanRequest\x12\x19\n" +
	"\x04plan\x18\x01 \x01(\v2\x05.PlanR\x04plan\"\x14\n" +
	"\x12UpdatePlanResponse\"\x11\n" +
	"\x0fGetMealsRequest\"/\n" +
	"\x10GetMealsResponse\x12\x1b\n" +
	"\x05meals\x18\x01 \x03(\v2\x05.MealR\x05meals\".\n" +
	"\x11CreateMealRequest\x12\x19\n" +
	"\x04meal\x18\x01 \x01(\v2\x05.MealR\x04meal\"-\n" +
	"\x12CreateMealResponse\x12\x17\n" +
	"\ameal_id\x18\x01 \x01(\x03R\x06mealId\".\n" +
	"\x11UpdateMealRequest\x12\x19\n" +
	"\x04meal\x18\x01 \x01(\v2\x05.MealR\x04meal\"\x14\n" +
	"\x12UpdateMealResponse\"I\n" +
	"\x16UpdateMealImageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vimage_bytes\x18\x02 \x01(\fR\n" +
	"imageBytes\"\x19\n" +
	"\x17UpdateMealImageResponse\",\n" +
	"\x11DeleteMealRequest\x12\x17\n" +
	"\ameal_id\x18\x01 \x01(\x03R\x06mealId\"\x14\n" +
	"\x12DeleteMealResponse\"\x17\n" +
	"\x15GetIngredientsRequest\"G\n" +
	"\x16GetIngredientsResponse\x12-\n" +
	"\vingredients\x18\x01 \x03(\v2\v.IngredientR\vingredients\"F\n" +
	"\x17CreateIngredientRequest\x12+\n" +
	"\n" +
	"ingredient\x18\x01 \x01(\v2\v.IngredientR\n" +
	"ingredient\"?\n" +
	"\x18CreateIngredientResponse\x12#\n" +
	"\ringredient_id\x18\x01 \x01(\x03R\fingredientId\"F\n" +
	"\x17UpdateIngredientRequest\x12+\n" +
	"\n" +
	"ingredient\x18\x01 \x01(\v2\v.IngredientR\n" +
	"ingredient\"\x1a\n" +
	"\x18UpdateIngredientResponse\">\n" +
	"\x17DeleteIngredientRequest\x12#\n" +
	"\ringredient_id\x18\x01 \x01(\x03R\fingredientId\"\x1a\n" +
	"\x18DeleteIngredientResponse\" \n" +
	"\x1eGetIngredientCategoriesRequest\"k\n" +
	"\x1fGetIngredientCategoriesResponse\x12H\n" +
	"\x15ingredient_categories\x18\x01 \x03(\v2\x13.IngredientCategoryR\x14ingredientCategories\"g\n" +
	"\x1fCreateIngredientCategoryRequest\x12D\n" +
	"\x13ingredient_category\x18\x01 \x01(\v2\x13.IngredientCategoryR\x12ingredientCategory\"w\n" +
	" CreateIngredientCategoryResponse\x124\n" +
	"\x16ingredient_category_id\x18\x01 \x01(\x03R\x14ingredientCategoryId\x12\x1d\n" +
	"\n" +
	"sort_index\x18\x02 \x01(\x03R\tsortIndex\"g\n" +
	"\x1fUpdateIngredientCategoryRequest\x12D\n" +
	"\x13ingredient_category\x18\x01 \x01(\v2\x13.IngredientCategoryR\x12ingredientCategory\"\"\n" +
	" UpdateIngredientCategoryResponse\"W\n" +
	"\x1fDeleteIngredientCategoryRequest\x124\n" +
	"\x16ingredient_category_id\x18\x01 \x01(\x03R\x14ingredientCategoryId\"\"\n" +
	" DeleteIngredientCategoryResponse\"\x89\x01\n" +
	"\x1fSwapIngredientCategoriesRequest\x122\n" +
	"\x15ingredient_category_a\x18\x01 \x01(\x03R\x13ingredientCategoryA\x122\n" +
	"\x15ingredient_category_b\x18\x02 \x01(\x03R\x13ingredientCategoryB\"\"\n" +
	" SwapIngredientCategoriesResponse2\xfc\t\n" +
	"\x13ShoppingListService\x12,\n" +
	"\aGetPlan\x12\x0f.GetPlanRequest\x1a\x10.GetPlanResponse\x125\n" +
	"\n" +
	"UpdatePlan\x12\x12.UpdatePlanRequest\x1a\x13.UpdatePlanResponse\x12/\n" +
	"\bGetMeals\x12\x10.GetMealsRequest\x1a\x11.GetMealsResponse\x125\n" +
	"\n" +
	"CreateMeal\x12\x12.CreateMealRequest\x1a\x13.CreateMealResponse\x125\n" +
	"\n" +
	"UpdateMeal\x12\x12.UpdateMealRequest\x1a\x13.UpdateMealResponse\x12R\n" +
	"\x1dUpdateMealPreviewImageRequest\x12\x17.UpdateMealImageRequest\x1a\x18.UpdateMealImageResponse\x12V\n" +
	"!UpdateMealIngredientsImageRequest\x12\x17.UpdateMealImageRequest\x1a\x18.UpdateMealImageResponse\x125\n" +
	"\n" +
	"DeleteMeal\x12\x12.DeleteMealRequest\x1a\x13.DeleteMealResponse\x12A\n" +
	"\x0eGetIngredients\x12\x16.GetIngredientsRequest\x1a\x17.GetIngredientsResponse\x12G\n" +
	"\x10CreateIngredient\x12\x18.CreateIngredientRequest\x1a\x19.CreateIngredientResponse\x12G\n" +
	"\x10UpdateIngredient\x12\x18.UpdateIngredientRequest\x1a\x19.UpdateIngredientResponse\x12G\n" +
	"\x10DeleteIngredient\x12\x18.DeleteIngredientRequest\x1a\x19.DeleteIngredientResponse\x12\\\n" +
	"\x17GetIngredientCategories\x12\x1f.GetIngredientCategoriesRequest\x1a .GetIngredientCategoriesResponse\x12_\n" +
	"\x18CreateIngredientCategory\x12 .CreateIngredientCategoryRequest\x1a!.CreateIngredientCategoryResponse\x12_\n" +
	"\x18UpdateIngredientCategory\x12 .UpdateIngredientCategoryRequest\x1a!.UpdateIngredientCategoryResponse\x12_\n" +
	"\x18DeleteIngredientCategory\x12 .DeleteIngredientCategoryRequest\x1a!.DeleteIngredientCategoryResponse\x12_\n" +
	"\x18SwapIngredientCategories\x12 .SwapIngredientCategoriesRequest\x1a!.SwapIngredientCategoriesResponseBPB\x18ShoppingListServiceProtoP\x01Z2github.com/chrisjpalmer/shoppinglist/backend/genpbb\x06proto3"

var (
	file_shopping_list_service_proto_rawDescOnce sync.Once
	file_shopping_list_service_proto_rawDescData []byte
)

func file_shopping_list_service_proto_rawDescGZIP() []byte {
	file_shopping_list_service_proto_rawDescOnce.Do(func() {
		file_shopping_list_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shopping_list_service_proto_rawDesc), len(file_shopping_list_service_proto_rawDesc)))
	})
	return file_shopping_list_service_proto_rawDescData
}

var file_shopping_list_service_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_shopping_list_service_proto_goTypes = []any{
	(*GetPlanRequest)(nil),                   // 0: GetPlanRequest
	(*GetPlanResponse)(nil),                  // 1: GetPlanResponse
	(*UpdatePlanRequest)(nil),                // 2: UpdatePlanRequest
	(*UpdatePlanResponse)(nil),               // 3: UpdatePlanResponse
	(*GetMealsRequest)(nil),                  // 4: GetMealsRequest
	(*GetMealsResponse)(nil),                 // 5: GetMealsResponse
	(*CreateMealRequest)(nil),                // 6: CreateMealRequest
	(*CreateMealResponse)(nil),               // 7: CreateMealResponse
	(*UpdateMealRequest)(nil),                // 8: UpdateMealRequest
	(*UpdateMealResponse)(nil),               // 9: UpdateMealResponse
	(*UpdateMealImageRequest)(nil),           // 10: UpdateMealImageRequest
	(*UpdateMealImageResponse)(nil),          // 11: UpdateMealImageResponse
	(*DeleteMealRequest)(nil),                // 12: DeleteMealRequest
	(*DeleteMealResponse)(nil),               // 13: DeleteMealResponse
	(*GetIngredientsRequest)(nil),            // 14: GetIngredientsRequest
	(*GetIngredientsResponse)(nil),           // 15: GetIngredientsResponse
	(*CreateIngredientRequest)(nil),          // 16: CreateIngredientRequest
	(*CreateIngredientResponse)(nil),         // 17: CreateIngredientResponse
	(*UpdateIngredientRequest)(nil),          // 18: UpdateIngredientRequest
	(*UpdateIngredientResponse)(nil),         // 19: UpdateIngredientResponse
	(*DeleteIngredientRequest)(nil),          // 20: DeleteIngredientRequest
	(*DeleteIngredientResponse)(nil),         // 21: DeleteIngredientResponse
	(*GetIngredientCategoriesRequest)(nil),   // 22: GetIngredientCategoriesRequest
	(*GetIngredientCategoriesResponse)(nil),  // 23: GetIngredientCategoriesResponse
	(*CreateIngredientCategoryRequest)(nil),  // 24: CreateIngredientCategoryRequest
	(*CreateIngredientCategoryResponse)(nil), // 25: CreateIngredientCategoryResponse
	(*UpdateIngredientCategoryRequest)(nil),  // 26: UpdateIngredientCategoryRequest
	(*UpdateIngredientCategoryResponse)(nil), // 27: UpdateIngredientCategoryResponse
	(*DeleteIngredientCategoryRequest)(nil),  // 28: DeleteIngredientCategoryRequest
	(*DeleteIngredientCategoryResponse)(nil), // 29: DeleteIngredientCategoryResponse
	(*SwapIngredientCategoriesRequest)(nil),  // 30: SwapIngredientCategoriesRequest
	(*SwapIngredientCategoriesResponse)(nil), // 31: SwapIngredientCategoriesResponse
	(*Plan)(nil),                             // 32: Plan
	(*PlanSummary)(nil),                      // 33: PlanSummary
	(*Meal)(nil),                             // 34: Meal
	(*Ingredient)(nil),                       // 35: Ingredient
	(*IngredientCategory)(nil),               // 36: IngredientCategory
}
var file_shopping_list_service_proto_depIdxs = []int32{
	32, // 0: GetPlanResponse.plan:type_name -> Plan
	33, // 1: GetPlanResponse.plan_summary:type_name -> PlanSummary
	32, // 2: UpdatePlanRequest.plan:type_name -> Plan
	34, // 3: GetMealsResponse.meals:type_name -> Meal
	34, // 4: CreateMealRequest.meal:type_name -> Meal
	34, // 5: UpdateMealRequest.meal:type_name -> Meal
	35, // 6: GetIngredientsResponse.ingredients:type_name -> Ingredient
	35, // 7: CreateIngredientRequest.ingredient:type_name -> Ingredient
	35, // 8: UpdateIngredientRequest.ingredient:type_name -> Ingredient
	36, // 9: GetIngredientCategoriesResponse.ingredient_categories:type_name -> IngredientCategory
	36, // 10: CreateIngredientCategoryRequest.ingredient_category:type_name -> IngredientCategory
	36, // 11: UpdateIngredientCategoryRequest.ingredient_category:type_name -> IngredientCategory
	0,  // 12: ShoppingListService.GetPlan:input_type -> GetPlanRequest
	2,  // 13: ShoppingListService.UpdatePlan:input_type -> UpdatePlanRequest
	4,  // 14: ShoppingListService.GetMeals:input_type -> GetMealsRequest
	6,  // 15: ShoppingListService.CreateMeal:input_type -> CreateMealRequest
	8,  // 16: ShoppingListService.UpdateMeal:input_type -> UpdateMealRequest
	10, // 17: ShoppingListService.UpdateMealPreviewImageRequest:input_type -> UpdateMealImageRequest
	10, // 18: ShoppingListService.UpdateMealIngredientsImageRequest:input_type -> UpdateMealImageRequest
	12, // 19: ShoppingListService.DeleteMeal:input_type -> DeleteMealRequest
	14, // 20: ShoppingListService.GetIngredients:input_type -> GetIngredientsRequest
	16, // 21: ShoppingListService.CreateIngredient:input_type -> CreateIngredientRequest
	18, // 22: ShoppingListService.UpdateIngredient:input_type -> UpdateIngredientRequest
	20, // 23: ShoppingListService.DeleteIngredient:input_type -> DeleteIngredientRequest
	22, // 24: ShoppingListService.GetIngredientCategories:input_type -> GetIngredientCategoriesRequest
	24, // 25: ShoppingListService.CreateIngredientCategory:input_type -> CreateIngredientCategoryRequest
	26, // 26: ShoppingListService.UpdateIngredientCategory:input_type -> UpdateIngredientCategoryRequest
	28, // 27: ShoppingListService.DeleteIngredientCategory:input_type -> DeleteIngredientCategoryRequest
	30, // 28: ShoppingListService.SwapIngredientCategories:input_type -> SwapIngredientCategoriesRequest
	1,  // 29: ShoppingListService.GetPlan:output_type -> GetPlanResponse
	3,  // 30: ShoppingListService.UpdatePlan:output_type -> UpdatePlanResponse
	5,  // 31: ShoppingListService.GetMeals:output_type -> GetMealsResponse
	7,  // 32: ShoppingListService.CreateMeal:output_type -> CreateMealResponse
	9,  // 33: ShoppingListService.UpdateMeal:output_type -> UpdateMealResponse
	11, // 34: ShoppingListService.UpdateMealPreviewImageRequest:output_type -> UpdateMealImageResponse
	11, // 35: ShoppingListService.UpdateMealIngredientsImageRequest:output_type -> UpdateMealImageResponse
	13, // 36: ShoppingListService.DeleteMeal:output_type -> DeleteMealResponse
	15, // 37: ShoppingListService.GetIngredients:output_type -> GetIngredientsResponse
	17, // 38: ShoppingListService.CreateIngredient:output_type -> CreateIngredientResponse
	19, // 39: ShoppingListService.UpdateIngredient:output_type -> UpdateIngredientResponse
	21, // 40: ShoppingListService.DeleteIngredient:output_type -> DeleteIngredientResponse
	23, // 41: ShoppingListService.GetIngredientCategories:output_type -> GetIngredientCategoriesResponse
	25, // 42: ShoppingListService.CreateIngredientCategory:output_type -> CreateIngredientCategoryResponse
	27, // 43: ShoppingListService.UpdateIngredientCategory:output_type -> UpdateIngredientCategoryResponse
	29, // 44: ShoppingListService.DeleteIngredientCategory:output_type -> DeleteIngredientCategoryResponse
	31, // 45: ShoppingListService.SwapIngredientCategories:output_type -> SwapIngredientCategoriesResponse
	29, // [29:46] is the sub-list for method output_type
	12, // [12:29] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_shopping_list_service_proto_init() }
func file_shopping_list_service_proto_init() {
	if File_shopping_list_service_proto != nil {
		return
	}
	file_plan_proto_init()
	file_meal_proto_init()
	file_ingredient_proto_init()
	file_ingredient_category_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shopping_list_service_proto_rawDesc), len(file_shopping_list_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shopping_list_service_proto_goTypes,
		DependencyIndexes: file_shopping_list_service_proto_depIdxs,
		MessageInfos:      file_shopping_list_service_proto_msgTypes,
	}.Build()
	File_shopping_list_service_proto = out.File
	file_shopping_list_service_proto_goTypes = nil
	file_shopping_list_service_proto_depIdxs = nil
}
