// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"dagger/backend/internal/dagger"

	"github.com/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject interface {
	querybuilder.GraphQLMarshaller
	ID(ctx context.Context) (dagger.ID, error)
}

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r Backend) MarshalJSON() ([]byte, error) {
	var concrete struct {
		RootSrc *dagger.Directory
		Src     *dagger.Directory
	}
	concrete.RootSrc = r.RootSrc
	concrete.Src = r.Src
	return json.Marshal(&concrete)
}

func (r *Backend) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		RootSrc *dagger.Directory
		Src     *dagger.Directory
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.RootSrc = concrete.RootSrc
	r.Src = concrete.Src
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "Backend":
		switch fnName {
		case "BackendService":
			var parent Backend
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var ws *dagger.Workspace
			if inputArgs["ws"] != nil {
				err = json.Unmarshal([]byte(inputArgs["ws"]), &ws)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg ws", err))
				}
			}
			return (*Backend).BackendService(&parent, ctx, ws)
		case "BuildCheck":
			var parent Backend
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Backend).BuildCheck(&parent, ctx)
		case "GenerateProtos":
			var parent Backend
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Backend).GenerateProtos(&parent), nil
		case "GenerateSqlc":
			var parent Backend
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Backend).GenerateSqlc(&parent), nil
		case "GenerateTailwind":
			var parent Backend
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Backend).GenerateTailwind(&parent, ctx)
		case "GenerateTempl":
			var parent Backend
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Backend).GenerateTempl(&parent, ctx)
		case "MigrateCheck":
			var parent Backend
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Backend).MigrateCheck(&parent, ctx)
		case "MigrateLocal":
			var parent Backend
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var localdb *dagger.File
			if inputArgs["localdb"] != nil {
				err = json.Unmarshal([]byte(inputArgs["localdb"]), &localdb)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg localdb", err))
				}
			}
			return (*Backend).MigrateLocal(&parent, ctx, localdb), nil
		case "Publish":
			var parent Backend
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var tag string
			if inputArgs["tag"] != nil {
				err = json.Unmarshal([]byte(inputArgs["tag"]), &tag)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg tag", err))
				}
			}
			var registryPassword *dagger.Secret
			if inputArgs["registryPassword"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registryPassword"]), &registryPassword)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registryPassword", err))
				}
			}
			return nil, (*Backend).Publish(&parent, ctx, tag, registryPassword)
		case "TestMigrationToolsNODB":
			var parent Backend
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Backend).TestMigrationToolsNODB(&parent, ctx)
		case "TestMigrationToolsNODBEnv":
			var parent Backend
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Backend).TestMigrationToolsNODBEnv(&parent, ctx)
		case "TestMigrationToolsWithDB":
			var parent Backend
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Backend).TestMigrationToolsWithDB(&parent, ctx)
		case "":
			var parent Backend
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var ws *dagger.Workspace
			if inputArgs["ws"] != nil {
				err = json.Unmarshal([]byte(inputArgs["ws"]), &ws)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg ws", err))
				}
			}
			return New(ws), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "":
		return dag.Module().
			WithDescription("A generated module for Backend functions\n\nThis module has been generated via dagger init and serves as a reference to\nbasic module structure as you get started with Dagger.\n\nTwo functions have been pre-created. You can modify, delete, or add to them,\nas needed. They demonstrate usage of arguments and return types using simple\necho and grep commands. The functions can be called from the dagger CLI or\nfrom one of the SDKs.\n\nThe first line in this comment block is a short description line and the\nrest is a long description with more detail on the module's purpose or usage,\nif appropriate. All modules should have a short description.\n").
			WithObject(
				dag.TypeDef().WithObject("Backend", dagger.TypeDefWithObjectOpts{SourceMap: dag.SourceMap("main.go", 25, 6)}).
					WithFunction(
						dag.Function("BackendService",
							dag.TypeDef().WithObject("Service")).
							WithDescription("BackendService - runs the backend service inside a container").
							WithSourceMap(dag.SourceMap("service.go", 17, 1)).
							WithUp().
							WithArg("ws", dag.TypeDef().WithObject("Workspace"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("service.go", 17, 55)})).
					WithFunction(
						dag.Function("BuildCheck",
							dag.TypeDef().WithObject("Container")).
							WithSourceMap(dag.SourceMap("build.go", 14, 1)).
							WithCheck()).
					WithFunction(
						dag.Function("GenerateProtos",
							dag.TypeDef().WithObject("Changeset")).
							WithDescription("GenerateProtos - generate protobuf codegen from .proto files").
							WithSourceMap(dag.SourceMap("generated.go", 11, 1)).
							WithGenerator()).
					WithFunction(
						dag.Function("GenerateSqlc",
							dag.TypeDef().WithObject("Changeset")).
							WithDescription("GenerateSqlc - generate sqlc codegen from .sql files").
							WithSourceMap(dag.SourceMap("generated.go", 26, 1)).
							WithGenerator()).
					WithFunction(
						dag.Function("GenerateTailwind",
							dag.TypeDef().WithObject("Changeset")).
							WithDescription("GenerateTailwind generates the maintw.css file using tailwindcss").
							WithSourceMap(dag.SourceMap("generated_tailwind.go", 12, 1)).
							WithGenerator()).
					WithFunction(
						dag.Function("GenerateTempl",
							dag.TypeDef().WithObject("Changeset")).
							WithDescription("GenerateTempl - generate templ codegen from .templ files").
							WithSourceMap(dag.SourceMap("generated.go", 40, 1)).
							WithGenerator()).
					WithFunction(
						dag.Function("MigrateCheck",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("MigrateCheck - checks whether the previous schema on the master branch\ncan be successfully migrated to the new schema").
							WithSourceMap(dag.SourceMap("migrate.go", 23, 1)).
							WithCheck()).
					WithFunction(
						dag.Function("MigrateLocal",
							dag.TypeDef().WithObject("File")).
							WithDescription("MigrateLocal - migrates the passed in database and returns it").
							WithSourceMap(dag.SourceMap("migrate.go", 14, 1)).
							WithArg("localdb", dag.TypeDef().WithObject("File"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("migrate.go", 14, 53)})).
					WithFunction(
						dag.Function("Publish",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithCachePolicy(dagger.FunctionCachePolicyNever).
							WithSourceMap(dag.SourceMap("main.go", 42, 1)).
							WithArg("tag", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 44, 2)}).
							WithArg("registryPassword", dag.TypeDef().WithObject("Secret"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 45, 2)})).
					WithFunction(
						dag.Function("TestMigrationToolsNODB",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("TestMigrationToolsNODB - tests that the migration tools work if the DB doesn't exist").
							WithSourceMap(dag.SourceMap("migration_tools.go", 46, 1)).
							WithCheck()).
					WithFunction(
						dag.Function("TestMigrationToolsNODBEnv",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("TestMigrationToolsNoDBEnv - tests that the migration tools correctly fail if the DATABASE_FILE var isn't present").
							WithSourceMap(dag.SourceMap("migration_tools.go", 59, 1)).
							WithCheck()).
					WithFunction(
						dag.Function("TestMigrationToolsWithDB",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("TestMigrationToolsWithDB - tests that the migration tools work if the DB exists").
							WithSourceMap(dag.SourceMap("migration_tools.go", 28, 1)).
							WithCheck()).
					WithConstructor(
						dag.Function("New",
							dag.TypeDef().WithObject("Backend")).
							WithSourceMap(dag.SourceMap("main.go", 32, 1)).
							WithArg("ws", dag.TypeDef().WithObject("Workspace"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 33, 2)}))), nil
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
