// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

type Frontend struct { // frontend (../../../../:0:0)
	query *querybuilder.Selection

	id      *ID
	publish *Void
}

func (r *Frontend) WithGraphQLQuery(q *querybuilder.Selection) *Frontend {
	return &Frontend{
		query: q,
	}
}

func (r *Frontend) BuildCheck() *Container {
	q := r.query.Select("buildCheck")

	return &Container{
		query: q,
	}
}

// FrontendService - runs the frontend service inside a container
func (r *Frontend) FrontendService() *Service {
	q := r.query.Select("frontendService")

	return &Service{
		query: q,
	}
}

// GenerateProtos - generate protobuf codegen from .proto files
func (r *Frontend) GenerateProtos() *Changeset {
	q := r.query.Select("generateProtos")

	return &Changeset{
		query: q,
	}
}

// A unique identifier for this Frontend.
func (r *Frontend) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Frontend) XXX_GraphQLType() string {
	return "Frontend"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Frontend) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Frontend) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Frontend) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Frontend) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Frontend{query: selectNode(dag.query, id, "Frontend")}
	return nil
}

func (r *Frontend) Publish(ctx context.Context, tag string, registryPassword *Secret) error {
	assertNotNil("registryPassword", registryPassword)
	if r.publish != nil {
		return nil
	}
	q := r.query.Select("publish")
	q = q.Arg("tag", tag)
	q = q.Arg("registryPassword", registryPassword)

	return q.Execute(ctx)
}

func (r *Frontend) Src() *Directory {
	q := r.query.Select("src")

	return &Directory{
		query: q,
	}
}

func (r *Query) Frontend(ws *Workspace) *Frontend { // frontend (../../../../:0:0)
	assertNotNil("ws", ws)
	q := r.query.Select("frontend")
	q = q.Arg("ws", ws)

	return &Frontend{
		query: q,
	}
}
