// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"dagger/migration-tools/internal/dagger"

	"github.com/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject interface {
	querybuilder.GraphQLMarshaller
	ID(ctx context.Context) (dagger.ID, error)
}

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r MigrationTools) MarshalJSON() ([]byte, error) {
	var concrete struct{}
	return json.Marshal(&concrete)
}

func (r *MigrationTools) UnmarshalJSON(bs []byte) error {
	var concrete struct{}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "MigrationTools":
		switch fnName {
		case "CheckMigrationValid":
			var parent MigrationTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var prevSchemaSql *dagger.File
			if inputArgs["prevSchemaSQL"] != nil {
				err = json.Unmarshal([]byte(inputArgs["prevSchemaSQL"]), &prevSchemaSql)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg prevSchemaSQL", err))
				}
			}
			var newSchemaSql *dagger.File
			if inputArgs["newSchemaSQL"] != nil {
				err = json.Unmarshal([]byte(inputArgs["newSchemaSQL"]), &newSchemaSql)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg newSchemaSQL", err))
				}
			}
			return nil, (*MigrationTools).CheckMigrationValid(&parent, ctx, prevSchemaSql, newSchemaSql)
		case "InstallMigrationTools":
			var parent MigrationTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var ctr *dagger.Container
			if inputArgs["ctr"] != nil {
				err = json.Unmarshal([]byte(inputArgs["ctr"]), &ctr)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg ctr", err))
				}
			}
			return (*MigrationTools).InstallMigrationTools(&parent, ctr), nil
		case "MigrateDatabase":
			var parent MigrationTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var db *dagger.File
			if inputArgs["db"] != nil {
				err = json.Unmarshal([]byte(inputArgs["db"]), &db)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg db", err))
				}
			}
			var schemaSql *dagger.File
			if inputArgs["schemaSQL"] != nil {
				err = json.Unmarshal([]byte(inputArgs["schemaSQL"]), &schemaSql)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg schemaSQL", err))
				}
			}
			return (*MigrationTools).MigrateDatabase(&parent, ctx, db, schemaSql), nil
		case "MountSchemaSQL":
			var parent MigrationTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var ctr *dagger.Container
			if inputArgs["ctr"] != nil {
				err = json.Unmarshal([]byte(inputArgs["ctr"]), &ctr)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg ctr", err))
				}
			}
			var schemaSql *dagger.File
			if inputArgs["schemaSQL"] != nil {
				err = json.Unmarshal([]byte(inputArgs["schemaSQL"]), &schemaSql)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg schemaSQL", err))
				}
			}
			return (*MigrationTools).MountSchemaSQL(&parent, ctr, schemaSql), nil
		case "TestMigrationToolsNODB":
			var parent MigrationTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*MigrationTools).TestMigrationToolsNODB(&parent, ctx)
		case "TestMigrationToolsNODBEnv":
			var parent MigrationTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*MigrationTools).TestMigrationToolsNODBEnv(&parent, ctx)
		case "TestMigrationToolsWithDB":
			var parent MigrationTools
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*MigrationTools).TestMigrationToolsWithDB(&parent, ctx)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "":
		return dag.Module().
			WithObject(
				dag.TypeDef().WithObject("MigrationTools", dagger.TypeDefWithObjectOpts{SourceMap: dag.SourceMap("main.go", 12, 6)}).
					WithFunction(
						dag.Function("CheckMigrationValid",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("CheckMigrationValid - checks whether a migration from the previous schema to the new schema succeeds.").
							WithSourceMap(dag.SourceMap("main.go", 21, 1)).
							WithArg("prevSchemaSQL", dag.TypeDef().WithObject("File"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 21, 67)}).
							WithArg("newSchemaSQL", dag.TypeDef().WithObject("File"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 21, 95)})).
					WithFunction(
						dag.Function("InstallMigrationTools",
							dag.TypeDef().WithObject("Container")).
							WithDescription("InstallMigrationTools - installs the migration tools into the specified container").
							WithSourceMap(dag.SourceMap("main.go", 49, 1)).
							WithArg("ctr", dag.TypeDef().WithObject("Container"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 49, 48)})).
					WithFunction(
						dag.Function("MigrateDatabase",
							dag.TypeDef().WithObject("File")).
							WithDescription("MigrateDatabase - migrates the passed in database, to the provided schema and returns it").
							WithSourceMap(dag.SourceMap("main.go", 16, 1)).
							WithArg("db", dag.TypeDef().WithObject("File"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 16, 63)}).
							WithArg("schemaSQL", dag.TypeDef().WithObject("File"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 16, 80)})).
					WithFunction(
						dag.Function("MountSchemaSQL",
							dag.TypeDef().WithObject("Container")).
							WithDescription("MountSchemaSQL - installs the migration sql into the expected location").
							WithSourceMap(dag.SourceMap("main.go", 61, 1)).
							WithArg("ctr", dag.TypeDef().WithObject("Container"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 61, 41)}).
							WithArg("schemaSQL", dag.TypeDef().WithObject("File"), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("main.go", 61, 64)})).
					WithFunction(
						dag.Function("TestMigrationToolsNODB",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("TestMigrationToolsNODB - tests that the migration tools work if the DB doesn't exist").
							WithSourceMap(dag.SourceMap("main.go", 85, 1)).
							WithCheck()).
					WithFunction(
						dag.Function("TestMigrationToolsNODBEnv",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("TestMigrationToolsNoDBEnv - tests that the migration tools correctly fail if the DATABASE_FILE var isn't present").
							WithSourceMap(dag.SourceMap("main.go", 100, 1)).
							WithCheck()).
					WithFunction(
						dag.Function("TestMigrationToolsWithDB",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("TestMigrationToolsWithDB - tests that the migration tools work if the DB exists").
							WithSourceMap(dag.SourceMap("main.go", 67, 1)).
							WithCheck())), nil
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
