name = "shoppinglist"
engineVersion = "v0.21.7"

[runtime]
  source = "go"

[[dependencies]]
  name = "backend"
  source = "../../../backend/.dagger"

[[dependencies]]
  name = "frontend"
  source = "../../../frontend/.dagger"

[[dependencies]]
  name = "helm"
  source = "../helm"

[codegen]
  automaticGitignore = false
