// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

func (r *Query) Shoppinglist(ws *Workspace) *Shoppinglist { // shoppinglist (../../../../../:0:0)
	assertNotNil("ws", ws)
	q := r.query.Select("shoppinglist")
	q = q.Arg("ws", ws)

	return &Shoppinglist{
		query: q,
	}
}

type Shoppinglist struct { // shoppinglist (../../../../../:0:0)
	query *querybuilder.Selection

	build          *Void
	buildAndDeploy *Void
	deploy         *Void
	id             *ID
}

func (r *Shoppinglist) WithGraphQLQuery(q *querybuilder.Selection) *Shoppinglist {
	return &Shoppinglist{
		query: q,
	}
}

func (r *Shoppinglist) Backend() *Directory {
	q := r.query.Select("backend")

	return &Directory{
		query: q,
	}
}

func (r *Shoppinglist) Build(ctx context.Context, ws *Workspace, tag string, registryPassword *Secret) error {
	assertNotNil("ws", ws)
	assertNotNil("registryPassword", registryPassword)
	if r.build != nil {
		return nil
	}
	q := r.query.Select("build")
	q = q.Arg("ws", ws)
	q = q.Arg("tag", tag)
	q = q.Arg("registryPassword", registryPassword)

	return q.Execute(ctx)
}

func (r *Shoppinglist) BuildAndDeploy(ctx context.Context, ws *Workspace, registryPassword *Secret, kubeEnv1 *Secret, kubeEnv2 *Secret) error {
	assertNotNil("ws", ws)
	assertNotNil("registryPassword", registryPassword)
	assertNotNil("kubeEnv1", kubeEnv1)
	assertNotNil("kubeEnv2", kubeEnv2)
	if r.buildAndDeploy != nil {
		return nil
	}
	q := r.query.Select("buildAndDeploy")
	q = q.Arg("ws", ws)
	q = q.Arg("registryPassword", registryPassword)
	q = q.Arg("kubeEnv1", kubeEnv1)
	q = q.Arg("kubeEnv2", kubeEnv2)

	return q.Execute(ctx)
}

func (r *Shoppinglist) Deploy(ctx context.Context, env string, tag string, kubectlFile *Secret, planningSiteUrl string, backendUrl string, shoppingSiteUrl string) error {
	assertNotNil("kubectlFile", kubectlFile)
	if r.deploy != nil {
		return nil
	}
	q := r.query.Select("deploy")
	q = q.Arg("env", env)
	q = q.Arg("tag", tag)
	q = q.Arg("kubectlFile", kubectlFile)
	q = q.Arg("planningSiteUrl", planningSiteUrl)
	q = q.Arg("backendUrl", backendUrl)
	q = q.Arg("shoppingSiteUrl", shoppingSiteUrl)

	return q.Execute(ctx)
}

func (r *Shoppinglist) Frontend() *Directory {
	q := r.query.Select("frontend")

	return &Directory{
		query: q,
	}
}

// A unique identifier for this Shoppinglist.
func (r *Shoppinglist) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Shoppinglist) XXX_GraphQLType() string {
	return "Shoppinglist"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Shoppinglist) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Shoppinglist) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Shoppinglist) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Shoppinglist) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Shoppinglist{query: selectNode(dag.query, id, "Shoppinglist")}
	return nil
}
