// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"dagger.io/dagger/querybuilder"
)

// The `RegistryConfigID` scalar type represents an identifier for an object of type RegistryConfig.
type RegistryConfigID string // registry-config (https://github.com/dagger/dagger/tree/d8811256e5e901e6760f7011431080fedd61fc47/toolchains/release/registry-config/main.go#L22)

// The `RegistryConfigSecretMountID` scalar type represents an identifier for an object of type RegistryConfigSecretMount.
type RegistryConfigSecretMountID string // registry-config (https://github.com/dagger/dagger/tree/d8811256e5e901e6760f7011431080fedd61fc47/toolchains/release/registry-config/main.go#L111)

// Retrieve the binding value, as type RegistryConfig
func (r *Binding) AsRegistryConfig() *RegistryConfig { // registry-config (https://github.com/dagger/dagger/tree/d8811256e5e901e6760f7011431080fedd61fc47/toolchains/release/registry-config/main.go#L22)
	q := r.query.Select("asRegistryConfig")

	return &RegistryConfig{
		query: q,
	}
}

// Retrieve the binding value, as type RegistryConfigSecretMount
func (r *Binding) AsRegistryConfigSecretMount() *RegistryConfigSecretMount { // registry-config (https://github.com/dagger/dagger/tree/d8811256e5e901e6760f7011431080fedd61fc47/toolchains/release/registry-config/main.go#L111)
	q := r.query.Select("asRegistryConfigSecretMount")

	return &RegistryConfigSecretMount{
		query: q,
	}
}

// Create or update a binding of type RegistryConfig in the environment
func (r *Env) WithRegistryConfigInput(name string, value *RegistryConfig, description string) *Env { // registry-config (https://github.com/dagger/dagger/tree/d8811256e5e901e6760f7011431080fedd61fc47/toolchains/release/registry-config/main.go#L22)
	assertNotNil("value", value)
	q := r.query.Select("withRegistryConfigInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired RegistryConfig output to be assigned in the environment
func (r *Env) WithRegistryConfigOutput(name string, description string) *Env { // registry-config (https://github.com/dagger/dagger/tree/d8811256e5e901e6760f7011431080fedd61fc47/toolchains/release/registry-config/main.go#L22)
	q := r.query.Select("withRegistryConfigOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Create or update a binding of type RegistryConfigSecretMount in the environment
func (r *Env) WithRegistryConfigSecretMountInput(name string, value *RegistryConfigSecretMount, description string) *Env { // registry-config (https://github.com/dagger/dagger/tree/d8811256e5e901e6760f7011431080fedd61fc47/toolchains/release/registry-config/main.go#L111)
	assertNotNil("value", value)
	q := r.query.Select("withRegistryConfigSecretMountInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired RegistryConfigSecretMount output to be assigned in the environment
func (r *Env) WithRegistryConfigSecretMountOutput(name string, description string) *Env { // registry-config (https://github.com/dagger/dagger/tree/d8811256e5e901e6760f7011431080fedd61fc47/toolchains/release/registry-config/main.go#L111)
	q := r.query.Select("withRegistryConfigSecretMountOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Load a RegistryConfig from its ID.
func (r *Query) LoadRegistryConfigFromID(id RegistryConfigID) *RegistryConfig { // registry-config (https://github.com/dagger/dagger/tree/d8811256e5e901e6760f7011431080fedd61fc47/toolchains/release/registry-config/main.go#L22)
	q := r.query.Select("loadRegistryConfigFromID")
	q = q.Arg("id", id)

	return &RegistryConfig{
		query: q,
	}
}

// Load a RegistryConfigSecretMount from its ID.
func (r *Query) LoadRegistryConfigSecretMountFromID(id RegistryConfigSecretMountID) *RegistryConfigSecretMount { // registry-config (https://github.com/dagger/dagger/tree/d8811256e5e901e6760f7011431080fedd61fc47/toolchains/release/registry-config/main.go#L111)
	q := r.query.Select("loadRegistryConfigSecretMountFromID")
	q = q.Arg("id", id)

	return &RegistryConfigSecretMount{
		query: q,
	}
}

// Create an OCI registry configuration file and use it safely with tools, like Helm or Oras.
//
// Tools interacting with an OCI registry usually have their own way to authenticate.
// Helm, for example, provides a command to "login" into a registry, which stores the credentials in a file.
// That is, however, not a safe way to store credentials, especially not in Dagger.
// Credentials persisted in the filesystem make their way into Dagger's layer cache.
//
// This module creates a configuration file and returns it as a Secret that can be mounted safely into a Container.
//
// Be advised that using the tool's built-in authentication mechanism may not work with the configuration file (since it's read only).
//
// You can read more about the topic in the readme: https://github.com/sagikazarmark/daggerverse/tree/main/registry-config#resources
func (r *Query) RegistryConfig() *RegistryConfig { // registry-config (https://github.com/dagger/dagger/tree/d8811256e5e901e6760f7011431080fedd61fc47/toolchains/release/registry-config/main.go#L22)
	q := r.query.Select("registryConfig")

	return &RegistryConfig{
		query: q,
	}
}

type RegistryConfig struct { // registry-config (https://github.com/dagger/dagger/tree/d8811256e5e901e6760f7011431080fedd61fc47/toolchains/release/registry-config/main.go#L22)
	query *querybuilder.Selection

	id *RegistryConfigID
}
type WithRegistryConfigFunc func(r *RegistryConfig) *RegistryConfig

// With calls the provided function with current RegistryConfig.
//
// This is useful for reusability and readability by not breaking the calling chain.
func (r *RegistryConfig) With(f WithRegistryConfigFunc) *RegistryConfig {
	return f(r)
}

func (r *RegistryConfig) WithGraphQLQuery(q *querybuilder.Selection) *RegistryConfig {
	return &RegistryConfig{
		query: q,
	}
}

// A unique identifier for this RegistryConfig.
func (r *RegistryConfig) ID(ctx context.Context) (RegistryConfigID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response RegistryConfigID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *RegistryConfig) XXX_GraphQLType() string {
	return "RegistryConfig"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *RegistryConfig) XXX_GraphQLIDType() string {
	return "RegistryConfigID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *RegistryConfig) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *RegistryConfig) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *RegistryConfig) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = *dag.LoadRegistryConfigFromID(RegistryConfigID(id))
	return nil
}

// RegistryConfigSecretOpts contains options for RegistryConfig.Secret
type RegistryConfigSecretOpts struct {
	//
	// Customize the name of the secret.
	//
	Name string // registry-config (https://github.com/dagger/dagger/tree/d8811256e5e901e6760f7011431080fedd61fc47/toolchains/release/registry-config/main.go#L60)
}

// Create the registry configuration.
func (r *RegistryConfig) Secret(opts ...RegistryConfigSecretOpts) *Secret { // registry-config (https://github.com/dagger/dagger/tree/d8811256e5e901e6760f7011431080fedd61fc47/toolchains/release/registry-config/main.go#L54)
	q := r.query.Select("secret")
	for i := len(opts) - 1; i >= 0; i-- {
		// `name` optional argument
		if !querybuilder.IsZeroValue(opts[i].Name) {
			q = q.Arg("name", opts[i].Name)
		}
	}

	return &Secret{
		query: q,
	}
}

// RegistryConfigSecretMountOpts contains options for RegistryConfig.SecretMount
type RegistryConfigSecretMountOpts struct {
	//
	// Name of the secret to create and mount.
	//
	SecretName string // registry-config (https://github.com/dagger/dagger/tree/d8811256e5e901e6760f7011431080fedd61fc47/toolchains/release/registry-config/main.go#L78)
	//
	// Skip mounting the secret if it's empty.
	//
	SkipOnEmpty bool // registry-config (https://github.com/dagger/dagger/tree/d8811256e5e901e6760f7011431080fedd61fc47/toolchains/release/registry-config/main.go#L83)
	//
	// A user:group to set for the mounted secret.
	//
	// The user and group can either be an ID (1000:1000) or a name (foo:bar).
	//
	// If the group is omitted, it defaults to the same as the user.
	//
	Owner string // registry-config (https://github.com/dagger/dagger/tree/d8811256e5e901e6760f7011431080fedd61fc47/toolchains/release/registry-config/main.go#L92)
	//
	// Permission given to the mounted secret (e.g., 0600).
	//
	// This option requires an owner to be set to be active.
	//
	Mode int // registry-config (https://github.com/dagger/dagger/tree/d8811256e5e901e6760f7011431080fedd61fc47/toolchains/release/registry-config/main.go#L99)
}

// Create a SecretMount that can be used to mount the registry configuration into a container.
func (r *RegistryConfig) SecretMount(path string, opts ...RegistryConfigSecretMountOpts) *RegistryConfigSecretMount { // registry-config (https://github.com/dagger/dagger/tree/d8811256e5e901e6760f7011431080fedd61fc47/toolchains/release/registry-config/main.go#L71)
	q := r.query.Select("secretMount")
	for i := len(opts) - 1; i >= 0; i-- {
		// `secretName` optional argument
		if !querybuilder.IsZeroValue(opts[i].SecretName) {
			q = q.Arg("secretName", opts[i].SecretName)
		}
		// `skipOnEmpty` optional argument
		if !querybuilder.IsZeroValue(opts[i].SkipOnEmpty) {
			q = q.Arg("skipOnEmpty", opts[i].SkipOnEmpty)
		}
		// `owner` optional argument
		if !querybuilder.IsZeroValue(opts[i].Owner) {
			q = q.Arg("owner", opts[i].Owner)
		}
		// `mode` optional argument
		if !querybuilder.IsZeroValue(opts[i].Mode) {
			q = q.Arg("mode", opts[i].Mode)
		}
	}
	q = q.Arg("path", path)

	return &RegistryConfigSecretMount{
		query: q,
	}
}

// Add credentials for a registry.
func (r *RegistryConfig) WithRegistryAuth(address string, username string, secret *Secret) *RegistryConfig { // registry-config (https://github.com/dagger/dagger/tree/d8811256e5e901e6760f7011431080fedd61fc47/toolchains/release/registry-config/main.go#L34)
	assertNotNil("secret", secret)
	q := r.query.Select("withRegistryAuth")
	q = q.Arg("address", address)
	q = q.Arg("username", username)
	q = q.Arg("secret", secret)

	return &RegistryConfig{
		query: q,
	}
}

// Removes credentials for a registry.
func (r *RegistryConfig) WithoutRegistryAuth(address string) *RegistryConfig { // registry-config (https://github.com/dagger/dagger/tree/d8811256e5e901e6760f7011431080fedd61fc47/toolchains/release/registry-config/main.go#L45)
	q := r.query.Select("withoutRegistryAuth")
	q = q.Arg("address", address)

	return &RegistryConfig{
		query: q,
	}
}

type RegistryConfigSecretMount struct { // registry-config (https://github.com/dagger/dagger/tree/d8811256e5e901e6760f7011431080fedd61fc47/toolchains/release/registry-config/main.go#L111)
	query *querybuilder.Selection

	id          *RegistryConfigSecretMountID
	mode        *int
	owner       *string
	path        *string
	secretName  *string
	skipOnEmpty *bool
}

func (r *RegistryConfigSecretMount) WithGraphQLQuery(q *querybuilder.Selection) *RegistryConfigSecretMount {
	return &RegistryConfigSecretMount{
		query: q,
	}
}

// A unique identifier for this RegistryConfigSecretMount.
func (r *RegistryConfigSecretMount) ID(ctx context.Context) (RegistryConfigSecretMountID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response RegistryConfigSecretMountID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *RegistryConfigSecretMount) XXX_GraphQLType() string {
	return "RegistryConfigSecretMount"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *RegistryConfigSecretMount) XXX_GraphQLIDType() string {
	return "RegistryConfigSecretMountID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *RegistryConfigSecretMount) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *RegistryConfigSecretMount) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *RegistryConfigSecretMount) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = *dag.LoadRegistryConfigSecretMountFromID(RegistryConfigSecretMountID(id))
	return nil
}

// Permission given to the mounted secret (e.g., 0600).
func (r *RegistryConfigSecretMount) Mode(ctx context.Context) (int, error) { // registry-config (https://github.com/dagger/dagger/tree/d8811256e5e901e6760f7011431080fedd61fc47/toolchains/release/registry-config/main.go#L125)
	if r.mode != nil {
		return *r.mode, nil
	}
	q := r.query.Select("mode")

	var response int

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

func (r *RegistryConfigSecretMount) Mount(container *Container) *Container { // registry-config (https://github.com/dagger/dagger/tree/d8811256e5e901e6760f7011431080fedd61fc47/toolchains/release/registry-config/main.go#L133)
	assertNotNil("container", container)
	q := r.query.Select("mount")
	q = q.Arg("container", container)

	return &Container{
		query: q,
	}
}

// A user:group to set for the mounted secret.
func (r *RegistryConfigSecretMount) Owner(ctx context.Context) (string, error) { // registry-config (https://github.com/dagger/dagger/tree/d8811256e5e901e6760f7011431080fedd61fc47/toolchains/release/registry-config/main.go#L122)
	if r.owner != nil {
		return *r.owner, nil
	}
	q := r.query.Select("owner")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Path to mount the secret into (a common path is ~/.docker/config.json).
func (r *RegistryConfigSecretMount) Path(ctx context.Context) (string, error) { // registry-config (https://github.com/dagger/dagger/tree/d8811256e5e901e6760f7011431080fedd61fc47/toolchains/release/registry-config/main.go#L113)
	if r.path != nil {
		return *r.path, nil
	}
	q := r.query.Select("path")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// DO NOT USE
// Made public until https://github.com/dagger/dagger/pull/8149 is fixed.
// private
func (r *RegistryConfigSecretMount) RegistryConfig() *RegistryConfig { // registry-config (https://github.com/dagger/dagger/tree/d8811256e5e901e6760f7011431080fedd61fc47/toolchains/release/registry-config/main.go#L130)
	q := r.query.Select("registryConfig")

	return &RegistryConfig{
		query: q,
	}
}

// Name of the secret to create and mount.
func (r *RegistryConfigSecretMount) SecretName(ctx context.Context) (string, error) { // registry-config (https://github.com/dagger/dagger/tree/d8811256e5e901e6760f7011431080fedd61fc47/toolchains/release/registry-config/main.go#L116)
	if r.secretName != nil {
		return *r.secretName, nil
	}
	q := r.query.Select("secretName")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// Skip mounting the secret if it's empty.
func (r *RegistryConfigSecretMount) SkipOnEmpty(ctx context.Context) (bool, error) { // registry-config (https://github.com/dagger/dagger/tree/d8811256e5e901e6760f7011431080fedd61fc47/toolchains/release/registry-config/main.go#L119)
	if r.skipOnEmpty != nil {
		return *r.skipOnEmpty, nil
	}
	q := r.query.Select("skipOnEmpty")

	var response bool

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}
