// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

type Backend struct { // backend (../../../../:0:0)
	query *querybuilder.Selection

	checkProtos               *Void
	checkSqlc                 *Void
	checkTailwind             *Void
	checkTempl                *Void
	id                        *ID
	migrateCheck              *Void
	publish                   *Void
	testMigrationToolsNodb    *Void
	testMigrationToolsNodbenv *Void
	testMigrationToolsWithDb  *Void
}

func (r *Backend) WithGraphQLQuery(q *querybuilder.Selection) *Backend {
	return &Backend{
		query: q,
	}
}

// BackendService - runs the backend service inside a container
func (r *Backend) BackendService(ws *Workspace) *Service {
	assertNotNil("ws", ws)
	q := r.query.Select("backendService")
	q = q.Arg("ws", ws)

	return &Service{
		query: q,
	}
}

func (r *Backend) BuildCheck() *Container {
	q := r.query.Select("buildCheck")

	return &Container{
		query: q,
	}
}

// CheckProtos - check that the working tree's proto generated files are in sync.
func (r *Backend) CheckProtos(ctx context.Context) error {
	if r.checkProtos != nil {
		return nil
	}
	q := r.query.Select("checkProtos")

	return q.Execute(ctx)
}

// CheckSqlc - check that the working tree's sqlc generated files are in sync.
func (r *Backend) CheckSqlc(ctx context.Context) error {
	if r.checkSqlc != nil {
		return nil
	}
	q := r.query.Select("checkSqlc")

	return q.Execute(ctx)
}

// CheckTailwind checks that maintw.css file is in sync
func (r *Backend) CheckTailwind(ctx context.Context) error {
	if r.checkTailwind != nil {
		return nil
	}
	q := r.query.Select("checkTailwind")

	return q.Execute(ctx)
}

// CheckTempl - check that the working tree's templ generated files are in sync.
func (r *Backend) CheckTempl(ctx context.Context) error {
	if r.checkTempl != nil {
		return nil
	}
	q := r.query.Select("checkTempl")

	return q.Execute(ctx)
}

// GenerateProtos - generate protobuf codegen from .proto files
func (r *Backend) GenerateProtos() *Changeset {
	q := r.query.Select("generateProtos")

	return &Changeset{
		query: q,
	}
}

// GenerateSqlc - generate sqlc codegen from .sql files
func (r *Backend) GenerateSqlc() *Changeset {
	q := r.query.Select("generateSqlc")

	return &Changeset{
		query: q,
	}
}

// GenerateTailwind generates the maintw.css file using tailwindcss
func (r *Backend) GenerateTailwind() *Changeset {
	q := r.query.Select("generateTailwind")

	return &Changeset{
		query: q,
	}
}

// GenerateTempl - generate templ codegen from .templ files
func (r *Backend) GenerateTempl() *Changeset {
	q := r.query.Select("generateTempl")

	return &Changeset{
		query: q,
	}
}

// A unique identifier for this Backend.
func (r *Backend) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Backend) XXX_GraphQLType() string {
	return "Backend"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Backend) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Backend) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Backend) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Backend) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Backend{query: selectNode(dag.query, id, "Backend")}
	return nil
}

// MigrateCheck - checks whether the previous schema on the master branch
// can be successfully migrated to the new schema
func (r *Backend) MigrateCheck(ctx context.Context) error {
	if r.migrateCheck != nil {
		return nil
	}
	q := r.query.Select("migrateCheck")

	return q.Execute(ctx)
}

// MigrateLocal - migrates the passed in database and returns it
func (r *Backend) MigrateLocal(localdb *File) *File {
	assertNotNil("localdb", localdb)
	q := r.query.Select("migrateLocal")
	q = q.Arg("localdb", localdb)

	return &File{
		query: q,
	}
}

func (r *Backend) Publish(ctx context.Context, tag string, registryPassword *Secret) error {
	assertNotNil("registryPassword", registryPassword)
	if r.publish != nil {
		return nil
	}
	q := r.query.Select("publish")
	q = q.Arg("tag", tag)
	q = q.Arg("registryPassword", registryPassword)

	return q.Execute(ctx)
}

// TestMigrationToolsNODB - tests that the migration tools work if the DB doesn't exist
func (r *Backend) TestMigrationToolsNodb(ctx context.Context) error {
	if r.testMigrationToolsNodb != nil {
		return nil
	}
	q := r.query.Select("testMigrationToolsNodb")

	return q.Execute(ctx)
}

// TestMigrationToolsNoDBEnv - tests that the migration tools correctly fail if the DATABASE_FILE var isn't present
func (r *Backend) TestMigrationToolsNodbenv(ctx context.Context) error {
	if r.testMigrationToolsNodbenv != nil {
		return nil
	}
	q := r.query.Select("testMigrationToolsNodbenv")

	return q.Execute(ctx)
}

// TestMigrationToolsWithDB - tests that the migration tools work if the DB exists
func (r *Backend) TestMigrationToolsWithDb(ctx context.Context) error {
	if r.testMigrationToolsWithDb != nil {
		return nil
	}
	q := r.query.Select("testMigrationToolsWithDb")

	return q.Execute(ctx)
}

func (r *Query) Backend(ws *Workspace) *Backend { // backend (../../../../:0:0)
	assertNotNil("ws", ws)
	q := r.query.Select("backend")
	q = q.Arg("ws", ws)

	return &Backend{
		query: q,
	}
}
